export type PlatformDetection={name:string;confidence:'likely'|'unknown';evidence:string[];scope:string;notice:string}
export function detectPlatform(html:string,url:string):PlatformDetection{
 const evidence:string[]=[],candidates:string[]=[]
 const assets=[...html.matchAll(/(?:src|href)=["']([^"']+)["']/gi)].map(m=>m[1])
 if(assets.some(x=>{try{return new URL(x,url).hostname==='cdn.imweb.me'}catch{return false}})){candidates.push('아임웹');evidence.push('아임웹 CDN의 이미지·파일 주소 확인')}
 if(/(?:EC_SHOP_MULTISHOP_SHIPPING|EC_FRONT|xans-element-)/.test(html)){candidates.push('카페24 쇼핑몰');evidence.push('카페24 쇼핑몰 전용 코드 패턴 확인')}
 if(assets.some(x=>/\/(?:wp-content|wp-includes)\//i.test(x))||/<meta[^>]+content=["']WordPress/i.test(html)){candidates.push('워드프레스');evidence.push('워드프레스 파일 경로 또는 생성기 정보 확인')}
 try{if(new URL(url).hostname.endsWith('.imweb.me')&&!candidates.includes('아임웹')){candidates.push('아임웹');evidence.push('아임웹 기본 도메인 확인')}}catch{}
 const name=candidates.length===1?candidates[0]:'미확인'
 return {name,confidence:name==='미확인'?'unknown':'likely',evidence,scope:name==='아임웹'?'콘텐츠·SEO 설정·지원되는 코드 삽입 범위 확인':name==='카페24 쇼핑몰'?'상품·페이지 설명·SEO 설정과 디자인 편집 권한 확인':name==='워드프레스'?'페이지 편집·SEO 도구·테마와 플러그인 수정 권한 확인':'관리자 화면과 제작사 정보 확인 필요',notice:candidates.length>1?'여러 플랫폼 흔적이 있어 확정할 수 없습니다.':'공개 페이지 기반 추정입니다. 실제 제작 환경·수정 권한·요금제는 별도 확인합니다.'}
}
export const websiteStatuses={existing:'홈페이지가 있어요',planning:'새로 만들고 싶어요',building:'다른 곳에서 제작 중이에요'} as const
export const websiteTypes={unknown:'아직 모름',business:'기업·전문 서비스',property:'분양·부동산',shop:'쇼핑몰',medical:'병원·의원',hotel:'호텔·숙박업',food:'음식점·카페',booking:'예약·서비스',other:'기타'} as const
export const industryMedia:Record<string,string[]>={business:['회사 외관·사무 공간','대표·구성원 프로필','서비스 제공 과정','제품·작업 사례'],property:['건물 외관·현장','실내 공간·모델하우스','입지·주변 환경','평면도·분양 자료'],shop:['상품 대표 사진','상세·소재·구성 사진','사용·착용 모습','상품 소개 영상'],medical:['병원 외관·진료 공간','진료 장면 (촬영 가능 여부 확인)','진료 장비','의료진·구성원 프로필'],hotel:['숙소 외관·진입 동선','객실·욕실','편의시설·공용 공간','객실·시설 소개 영상'],food:['외관·간판','내부·좌석 공간','대표 메뉴·음식 사진','조리 과정·메뉴 소개 영상'],booking:['시설·이용 공간','서비스 제공 과정','담당자·구성원 프로필','이용 방법 안내 영상'],other:['외관·사업 공간','서비스·상품 사진','구성원 프로필','사업 소개 영상'],unknown:['외관·사업 공간','서비스·상품 사진','구성원 프로필','사업 소개 영상']}
export const mediaSources={unknown:'아직 미정',provided:'고객이 보유 자료 제공',partial:'일부 제공·추가 제작 필요',stock:'사용 권한이 있는 이미지·영상 활용 요청',shoot:'새로 촬영 필요'} as const
export const websiteFeatures=['상담 신청','예약','결제','상품 판매','게시판','다국어','객실·요금 안내','예약 시스템 연동']
export function cleanWebsiteContext(x:any){if(!x||!Object.prototype.hasOwnProperty.call(websiteStatuses,x.status))return null;const enumValue=(v:any,values:string[])=>values.includes(v)?v:'unknown';return{status:x.status,creator:enumValue(x.creator,['self','agency','unknown']),editable:enumValue(x.editable,['yes','no','unknown']),agencyContact:enumValue(x.agencyContact,['yes','no','unknown']),platform:typeof x.platform==='string'?x.platform.trim().slice(0,120):'',purpose:typeof x.purpose==='string'?x.purpose.trim().slice(0,2000):'',siteType:Object.prototype.hasOwnProperty.call(websiteTypes,x.siteType)?x.siteType:'unknown',features:Array.isArray(x.features)?[...new Set(x.features.filter((v:any)=>websiteFeatures.includes(v)))]:[],requirements:typeof x.requirements==='string'?x.requirements.trim().slice(0,3000):'',content:typeof x.content==='string'?x.content.trim().slice(0,2000):'',reference:typeof x.reference==='string'?x.reference.trim().slice(0,2000):'',schedule:typeof x.schedule==='string'?x.schedule.trim().slice(0,500):'',budget:typeof x.budget==='string'?x.budget.trim().slice(0,500):'',photoSource:Object.prototype.hasOwnProperty.call(mediaSources,x.photoSource)?x.photoSource:'unknown',videoSource:Object.prototype.hasOwnProperty.call(mediaSources,x.videoSource)?x.videoSource:'unknown',mediaSubjects:Array.isArray(x.mediaSubjects)?[...new Set(x.mediaSubjects.filter((v:any)=>typeof v==='string'&&Object.values(industryMedia).some(list=>list.includes(v))))]:[],mediaDetails:typeof x.mediaDetails==='string'?x.mediaDetails.trim().slice(0,2000):''}}
export function websiteBrief(x:any){const c=cleanWebsiteContext(x);if(!c)return '';return `홈페이지 유형: ${websiteTypes[c.siteType as keyof typeof websiteTypes]}\n소개할 내용·강점: ${c.content||'추가 협의'}\n필요한 기능: ${c.features.join(', ')||'추가 협의'}\n요구사항: ${c.requirements||'추가 협의'}\n참고 사이트·디자인: ${c.reference||'미입력'}\n희망 일정: ${c.schedule||'미입력'}\n희망 예산: ${c.budget||'미입력'} (확정 견적 아님)\n사진·이미지: ${mediaSources[c.photoSource as keyof typeof mediaSources]}\n영상: ${mediaSources[c.videoSource as keyof typeof mediaSources]}\n선택한 촬영 대상: ${c.mediaSubjects.join(', ')||'추가 협의'}\n촬영·편집 요청: ${c.mediaDetails||'추가 협의'}\n촬영·편집·자료 구매 비용과 사용 권한은 별도 확인 후 견적에 반영합니다.`}
export function productionDirection(i:any,goal:any){return{summary:`${i.company_name}의 사업 정보와 희망 검색 목표를 바탕으로 홈페이지 제작 방향을 협의하는 자료입니다. 공개 홈페이지 측정 결과가 아닙니다.`,findings:[`확인: ${goal?.service||i.main_services||'주요 서비스 확인 필요'}를 우선 알리고 싶다고 접수했습니다. | 영향: 서비스 안내 페이지의 우선순위를 정하는 출발점입니다. | 근거: 고객 상담 접수 (사업 사실은 별도 확인)`,`확인: ${i.website_context?.purpose||'제작 목적과 진행 상황은 추가 확인이 필요합니다.'} | 영향: 제작 범위와 문의 동선을 협의할 수 있습니다. | 근거: 고객 상담 접수`],priorities:['실제 제공 서비스·고객·지역을 확인합니다 — 희망 목표와 사업 사실을 구분하기 위해서입니다.','핵심 서비스 안내·이용 조건·질문과 답변·문의 동선을 설계합니다 — 고객이 필요한 정보를 찾도록 하기 위해서입니다.','제작 범위·수정 권한·초기 측정 조건을 협의합니다 — 제작 완료 후 관리가 연결되도록 하기 위해서입니다.'],proposal:websiteBrief(i.website_context)+'\n\n'+'더담다에서 제작하면 검색·AI 진단과 향후 관리에 필요한 정보 구조를 함께 설계합니다. 타사 제작도 수정 가능한 범위에서 연계할 수 있습니다. 제작비와 이후 진단·월 관리비는 구분해 견적을 협의합니다.'}}
