-- 상담별 견적서. 직원 인증을 거친 서버에서만 읽고 쓴다.
create table if not exists public.discovery_quotations (
 id bigint generated by default as identity primary key,
 inquiry_id bigint not null unique references public.discovery_inquiries(id) on delete cascade,
 document jsonb not null,
 updated_at timestamptz not null default now()
);
alter table public.discovery_quotations enable row level security;
