-- 계약 전 네이버 상담 진단. 계약 이후에도 상담 건에 남겨 이력을 보존한다.
create table if not exists public.discovery_naver_inquiry_history (
  id bigint generated by default as identity primary key,
  inquiry_id bigint not null references public.discovery_inquiries(id) on delete cascade,
  query text not null,
  observed jsonb not null default '{}'::jsonb,
  interpreted text not null,
  created_at timestamptz not null default now()
);
create index if not exists discovery_naver_inquiry_history_inquiry_created_idx
  on public.discovery_naver_inquiry_history(inquiry_id,created_at desc);
alter table public.discovery_naver_inquiry_history enable row level security;
-- 직원 인증을 거친 서버의 service role만 조회·저장한다.
