-- Discovery improvement task/work log
create table if not exists public.discovery_improvement_tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.discovery_projects(id) on delete cascade,
  priority integer not null,
  title text not null,
  status text not null default 'completed' check (status in ('review_pending','work_pending','in_progress','completed','remeasure_pending','effect_confirmed','hold')),
  summary text,
  work_details text[] not null default '{}',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, priority)
);
alter table public.discovery_improvement_tasks enable row level security;
drop policy if exists "public read improvement tasks" on public.discovery_improvement_tasks;
create policy "public read improvement tasks" on public.discovery_improvement_tasks for select to anon, authenticated using (project_id=1);

insert into public.discovery_improvement_tasks(project_id,priority,title,status,summary,work_details,completed_at)
values (
  1,1,'검색·AI 발견 관리 핵심 서비스 체계 구축','completed',
  'Day 0 개선안 1번을 실제 서비스 흐름으로 구현하고 상담 접수부터 홈페이지 진단까지 한 사이클을 검증했습니다.',
  array[
    '기존 /ai-search 서비스 페이지를 검색·AI 발견 관리 흐름에 맞게 정비',
    '과장·보장형 표현을 측정·개선 중심 표현으로 수정',
    '전용 상담 페이지와 자동 상담 신청 폼 구축',
    '개인정보 수집·이용 고지 및 /privacy 개인정보처리방침 연결',
    '상담 정보를 discovery_inquiries에 저장하고 상담·진단 대기 목록에 연결',
    '진단 상세페이지에서 접수정보 확인 및 상태 변경 기능 구현',
    '접수 URL을 이용한 홈페이지 현황 확인 기능 연결',
    '테스트 상담 건으로 접수 → 목록 → 상세 → 진단·검토 상태 변경 → 홈페이지 확인 흐름 검증'
  ],
  now()
)
on conflict(project_id,priority) do update set
 title=excluded.title,status=excluded.status,summary=excluded.summary,work_details=excluded.work_details,completed_at=excluded.completed_at,updated_at=now();

-- V0.2: machine-checkable completion criteria
alter table public.discovery_improvement_tasks
  add column if not exists completion_criteria jsonb not null default '[]'::jsonb,
  add column if not exists verification_result jsonb,
  add column if not exists verified_at timestamptz;

insert into public.discovery_improvement_tasks(project_id,priority,title,status,summary,work_details,completion_criteria)
values (
  1,2,'검색 유입이 거의 없을 때 점검할 것 가이드 페이지','in_progress',
  '검색 유입이 적거나 줄었을 때 확인할 기본 항목을 공개 가이드로 제작하고 기술 조건을 검증합니다.',
  array[
    '/guide/search-traffic-checklist 신규 페이지 제작',
    '검색 유입 감소 원인을 단일 원인으로 단정하지 않는 점검 가이드 구성',
    'sitemap에 가이드 URL 추가',
    '/ai-search에서 가이드로 연결되는 내부 링크 추가'
  ],
  '[
    {"key":"page","label":"가이드 페이지가 정상 응답"},
    {"key":"metadata","label":"title과 description 존재"},
    {"key":"sitemap","label":"sitemap에 가이드 URL 포함"},
    {"key":"robots","label":"robots.txt에서 가이드 차단 없음"},
    {"key":"internalLink","label":"검색·AI 발견 관리 페이지에서 내부 링크 연결"},
    {"key":"consultingLink","label":"가이드에서 현재 상태 진단 신청으로 연결"},
    {"key":"safeCopy","label":"검색 순위·AI 추천 노출 보장 표현 없음"}
  ]'::jsonb
)
on conflict(project_id,priority) do update set
 title=excluded.title,status=excluded.status,summary=excluded.summary,work_details=excluded.work_details,
 completion_criteria=excluded.completion_criteria,updated_at=now();