-- Discovery 상담/진단 접수
-- Supabase SQL Editor에서 1회 실행

create table if not exists public.discovery_inquiries (
  id bigint generated by default as identity primary key,
  company_name text not null,
  website_url text not null,
  industry text,
  main_services text,
  concerns text[] not null default '{}',
  contact_name text not null,
  phone text,
  email text,
  message text,
  privacy_agreed boolean not null default false,
  status text not null default 'diagnosis_pending'
    check (status in ('diagnosis_pending','reviewing','proposal','converted','closed')),
  project_id bigint references public.discovery_projects(id) on delete set null,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.discovery_inquiries is '검색·AI 발견 관리 상담 및 진단 접수';
comment on column public.discovery_inquiries.status is 'diagnosis_pending=진단대기, reviewing=진단/검토중, proposal=진행협의, converted=프로젝트전환, closed=종료';

create index if not exists discovery_inquiries_status_idx
  on public.discovery_inquiries(status, created_at desc);

alter table public.discovery_inquiries enable row level security;

-- 공개 상담 페이지에서는 INSERT만 허용한다.
drop policy if exists "public can submit discovery inquiry" on public.discovery_inquiries;
create policy "public can submit discovery inquiry"
on public.discovery_inquiries
for insert
to anon, authenticated
with check (
  privacy_agreed = true
  and length(trim(company_name)) > 0
  and length(trim(website_url)) > 0
  and length(trim(contact_name)) > 0
  and (coalesce(length(trim(phone)),0) > 0 or coalesce(length(trim(email)),0) > 0)
  and status = 'diagnosis_pending'
  and project_id is null
  and internal_notes is null
);

-- 공개키로 상담 목록/연락처를 읽거나 수정하지 못하게 SELECT/UPDATE/DELETE 정책은 만들지 않는다.
-- 내부 관리 화면은 서버 전용 service role key를 사용해 조회/상태변경하도록 연결한다.
