-- Keep the evidence and interpretation attached to each project and measurement round.
create table if not exists public.discovery_analysis_history (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.discovery_projects(id) on delete cascade,
  measurement_round text not null default 'Day 0',
  observed jsonb not null default '[]'::jsonb,
  interpreted text not null,
  created_at timestamptz not null default now()
);
create index if not exists discovery_analysis_history_project_created_idx
  on public.discovery_analysis_history(project_id, created_at desc);
alter table public.discovery_analysis_history enable row level security;
-- Reads and writes use the server's service role after staff authentication.
