'use client'
import {useEffect,useState} from 'react'

type Series={data:{period:string;ratio:number}[];error?:string}
type Result={code:string;label:string;error?:string;items?:{title:string;description:string;link:string;address:string}[]}
type Report={project:string;query:string;checkedAt:string;results:Result[];trend:Series|null;shopping:(Series&{category:string})|null}
type History={id:number;interpreted:string;created_at:string;measurement_round:string;observed:{query:string}[]}
const options=[{code:'webkr',label:'웹문서'},{code:'blog',label:'블로그'},{code:'cafearticle',label:'카페글'},{code:'local',label:'지역'}]
const presets={local:{label:'지역 업체',channels:['webkr','blog','cafearticle','local']},service:{label:'서비스·전문직',channels:['webkr','blog','cafearticle']},commerce:{label:'온라인 판매',channels:['webkr','blog','cafearticle']}} as const

function Bars({series}:{series:Series}){
 if(series.error)return <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{series.error}</p>
 if(!series.data.length)return <p className="mt-4 text-sm text-gray-500">해당 기간의 추이 데이터가 없습니다.</p>
 return <div className="mt-5 space-y-2">{series.data.map(point=><div key={point.period} className="flex items-center gap-3 text-xs"><span className="w-24 shrink-0 text-gray-500">{point.period}</span><div className="h-5 flex-1 rounded bg-gray-100"><div className="h-5 rounded bg-[#10B981]" style={{width:`${Math.max(1,Math.min(100,point.ratio))}%`}}/></div><span className="w-10 text-right font-bold">{point.ratio.toFixed(1)}</span></div>)}</div>
}

export default function NaverExplorer({projects}:{projects:{id:number;name:string|null}[]}){
 const projectId=projects[0]?.id||0
 const[query,setQuery]=useState(''),[preset,setPreset]=useState<keyof typeof presets>('local'),[channels,setChannels]=useState<string[]>([...presets.local.channels]),[trend,setTrend]=useState(true),[shoppingCategory,setShoppingCategory]=useState('')
 const[report,setReport]=useState<Report|null>(null),[analysis,setAnalysis]=useState(''),[analysisId,setAnalysisId]=useState<number|null>(null),[clientDraft,setClientDraft]=useState(''),[approved,setApproved]=useState(false),[history,setHistory]=useState<History[]>([]),[busy,setBusy]=useState(false),[analyzing,setAnalyzing]=useState(false),[drafting,setDrafting]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 useEffect(()=>{setHistory([]);fetch(`/api/discovery/analysis-history?projectId=${projectId}&round=Naver`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>setHistory(data?.history||[])).catch(()=>{})},[projectId])
 function changePreset(value:keyof typeof presets){setPreset(value);setChannels([...presets[value].channels]);setTrend(true);if(value!=='commerce')setShoppingCategory('');setReport(null);setAnalysis('');setAnalysisId(null);setClientDraft('')}
 async function run(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setReport(null);setAnalysis('');setAnalysisId(null);setClientDraft('');setApproved(false)
  try{const response=await fetch('/api/discovery/naver-explore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,query,channels,trend,shoppingCategory:preset==='commerce'?shoppingCategory:''})});const data=await response.json();if(!response.ok)throw new Error(data.error||'조회에 실패했습니다.');setReport(data)}catch(e:any){setError(e.message||'조회에 실패했습니다.')}finally{setBusy(false)}
 }
 async function analyze(){if(!report)return;setAnalyzing(true);setError('')
  try{const response=await fetch('/api/discovery/analyze-naver',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,report})});const data=await response.json();if(!response.ok)throw new Error(data.error||'분석에 실패했습니다.');setAnalysis(data.analysis);setAnalysisId(data.history.id);setClientDraft('');setApproved(false);setHistory(previous=>[data.history,...previous])}catch(e:any){setError(e.message||'분석에 실패했습니다.')}finally{setAnalyzing(false)}
 }
 async function makeClientDraft(){if(!analysisId)return;setDrafting(true);setError('')
  try{const response=await fetch('/api/discovery/naver-deliverable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,historyId:analysisId})});const data=await response.json();if(!response.ok)throw new Error(data.error||'고객용 초안 생성 실패');setClientDraft(data.draft);setApproved(false)}catch(e:any){setError(e.message||'고객용 초안 생성 실패')}finally{setDrafting(false)}
 }
 async function approve(){if(!analysisId||!clientDraft.trim())return;setSaving(true);setError('')
  try{const response=await fetch('/api/discovery/naver-deliverable',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,historyId:analysisId,content:clientDraft})});const data=await response.json();if(!response.ok)throw new Error(data.error||'저장 실패');setApproved(true);setHistory(previous=>[data.history,...previous])}catch(e:any){setError(e.message||'저장 실패')}finally{setSaving(false)}
 }
 return <>
  <form onSubmit={run} className="space-y-5 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6">
   <label className="block max-w-xl text-sm font-bold">고객이 검색할 표현<input value={query} maxLength={80} required onChange={e=>setQuery(e.target.value)} placeholder="예: 인천공항 캐리어 배송" className="mt-2 w-full rounded-xl border border-gray-300 px-4 py-3 font-normal"/></label>
   <fieldset><legend className="text-sm font-bold">업체 유형</legend><div className="mt-2 flex flex-wrap gap-2">{Object.entries(presets).map(([code,item])=><button type="button" key={code} onClick={()=>changePreset(code as keyof typeof presets)} className={'rounded-full border px-4 py-2 text-sm font-bold '+(preset===code?'border-[#087A56] bg-emerald-50 text-[#087A56]':'border-gray-200')}>{item.label}</button>)}</div></fieldset>
   <fieldset><legend className="text-sm font-bold">조회할 네이버 자료</legend><div className="mt-2 flex flex-wrap gap-3">{options.map(item=><label key={item.code} className="flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-sm"><input type="checkbox" checked={channels.includes(item.code)} onChange={()=>setChannels(previous=>previous.includes(item.code)?previous.filter(x=>x!==item.code):[...previous,item.code])}/>{item.label}</label>)}<label className="flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-sm"><input type="checkbox" checked={trend} onChange={e=>setTrend(e.target.checked)}/>검색어 트렌드</label></div></fieldset>
   {preset==='commerce'&&<label className="block max-w-md text-sm font-bold">쇼핑 인사이트 · 네이버쇼핑 카테고리 코드<input value={shoppingCategory} inputMode="numeric" pattern="[0-9]{8,12}" onChange={e=>setShoppingCategory(e.target.value)} placeholder="상품이 있을 때 cat_id 입력 (선택)" className="mt-2 w-full rounded-xl border border-gray-300 px-4 py-3 font-normal"/><span className="mt-1 block text-xs font-normal text-gray-500">네이버쇼핑 카테고리 URL의 cat_id를 입력하면 해당 분야의 검색 클릭 추이를 함께 조회합니다.</span></label>}
   <button disabled={busy||!projectId} className="rounded-xl bg-[#0A0F1E] px-6 py-3 font-bold text-white disabled:opacity-50">{busy?'조회 중...':'선택 채널 조회'}</button>
  </form>
  {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
  {report&&<div className="mt-7 space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-gray-500">{report.project} · “{report.query}” · {new Date(report.checkedAt).toLocaleString('ko-KR')} 조회</p><button onClick={analyze} disabled={analyzing} className="rounded-xl bg-[#087A56] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{analyzing?'근거 분석 중...':'네이버 개선안 초안 만들기'}</button></div>
   {analysis&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-xl font-extrabold">1. 내부 진단·개선안 검토</h2><p className="mt-2 text-xs text-gray-600">조회 근거와 자동 분석이 이력에 저장됐습니다. 실제 서비스 범위와 공식 소유 정보, 개선 우선순위를 확인하세요.</p><div className="mt-4 whitespace-pre-wrap text-sm leading-7">{analysis}</div><button onClick={makeClientDraft} disabled={drafting} className="mt-5 rounded-xl bg-[#087A56] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{drafting?'고객용 문안 작성 중...':'2. 고객용 설명 초안 만들기'}</button></section>}
   {clientDraft&&<section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h2 className="text-xl font-extrabold">2. 고객에게 전달할 내용</h2><p className="mt-2 text-sm text-gray-600">사실 관계와 실행 가능한 개선 방향을 수정한 뒤 전달 준비로 확정하세요.</p><textarea value={clientDraft} onChange={e=>{setClientDraft(e.target.value);setApproved(false)}} rows={16} maxLength={12000} className="mt-4 w-full rounded-xl border border-blue-200 bg-white p-4 text-sm leading-7"/><div className="mt-3 flex flex-wrap items-center gap-3"><button onClick={approve} disabled={saving||clientDraft.trim().length<20} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?'저장 중...':'3. 검토 완료 · 전달 문안 저장'}</button>{approved&&<button onClick={()=>navigator.clipboard.writeText(clientDraft).catch(()=>setError('복사하지 못했습니다. 문안을 직접 선택해 복사해 주세요.'))} className="rounded-xl border border-blue-300 bg-white px-5 py-3 text-sm font-bold">전달 문안 복사</button>}{approved&&<span className="text-sm font-bold text-[#087A56]">검토 완료 · 전달 준비</span>}</div><p className="mt-3 text-xs text-gray-500">저장과 복사는 고객에게 자동 발송하지 않습니다. 실제 전달과 홈페이지 수정은 별도로 진행합니다.</p></section>}
   {report.trend&&<section className="rounded-2xl border border-gray-200 bg-white p-5 md:p-6"><h2 className="text-xl font-extrabold">검색어 트렌드</h2><p className="mt-2 text-sm text-gray-500">최근 약 90일의 주간 상대 검색 추이입니다. 실제 검색량이나 업체 노출 수는 아닙니다.</p><Bars series={report.trend}/></section>}
   {report.shopping&&<section className="rounded-2xl border border-gray-200 bg-white p-5 md:p-6"><h2 className="text-xl font-extrabold">쇼핑 검색 클릭 추이</h2><p className="mt-2 text-sm text-gray-500">선택한 카테고리 {report.shopping.category}에서 해당 검색어의 주간 상대 클릭 추이입니다. 판매량·매출이 아닙니다.</p><Bars series={report.shopping}/></section>}
   <div className="grid gap-5 lg:grid-cols-2">{report.results.map(channel=><section key={channel.code} className="rounded-2xl border border-gray-200 bg-white p-5 md:p-6"><h2 className="text-xl font-extrabold">{channel.label} 검색</h2><p className="mt-1 text-xs text-gray-500">네이버 API 결과 · {channel.error?'조회 실패':`표시 ${channel.items?.length||0}건`}</p>{channel.error?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{channel.error}</p>:channel.items?.length?<ol className="mt-4 divide-y divide-gray-100">{channel.items.map((item,index)=><li key={index} className="py-3"><span className="text-xs font-bold text-[#087A56]">{index+1}. </span>{/^https?:\/\//.test(item.link)?<a href={item.link} target="_blank" rel="noopener noreferrer" className="break-words text-sm font-bold hover:underline">{item.title}</a>:<span className="text-sm font-bold">{item.title}</span>}<p className="mt-1 line-clamp-2 text-xs leading-5 text-gray-500">{item.description||item.address}</p></li>)}</ol>:<p className="mt-4 text-sm text-gray-500">표시할 결과가 없습니다.</p>}</section>)}</div><p className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">분야별 API 결과는 실제 네이버 통합검색 화면의 순위·수집·색인 상태를 증명하지 않습니다. 다른 표현이나 시점의 결과도 달라질 수 있습니다.</p>
  </div>}
  {history.length>0&&<section className="mt-8 rounded-2xl border border-gray-200 bg-white p-5 md:p-6"><h2 className="text-xl font-extrabold">네이버 진단·전달 문안 이력</h2><div className="mt-4 space-y-3">{history.map(item=><details key={item.id} className="rounded-xl border border-gray-200 p-4"><summary className="cursor-pointer text-sm font-bold">{new Date(item.created_at).toLocaleString('ko-KR')} · {item.observed?.[0]?.query||'검색어'} · {item.measurement_round==='Naver Approved'?'검토 완료 문안':'내부 자동 분석'}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{item.interpreted}</p>{item.measurement_round==='Naver'&&<button onClick={()=>{setReport({project:projects.find(p=>p.id===projectId)?.name||'프로젝트',query:item.observed?.[0]?.query||'',checkedAt:item.created_at,results:[],trend:null,shopping:null});setAnalysis(item.interpreted);setAnalysisId(item.id);setClientDraft('');setApproved(false);window.scrollTo({top:0,behavior:'smooth'})}} className="mt-3 rounded-lg border border-emerald-300 px-3 py-2 text-xs font-bold">이 진단으로 고객 문안 만들기</button>}{item.measurement_round==='Naver Approved'&&<button onClick={()=>navigator.clipboard.writeText(item.interpreted).catch(()=>setError('복사하지 못했습니다. 문안을 직접 선택해 복사해 주세요.'))} className="mt-3 rounded-lg border border-blue-300 px-3 py-2 text-xs font-bold">전달 문안 복사</button>}</details>)}</div></section>}
 </>
}
