import {sameGoalSnapshot} from '../questionReview'
import type {NextTask} from '../improvementWorkflow'
import {validateJourney,selectionCriteria,journeyStages,SelectionJourney} from './selectionJourney'
export function journeyProposals(j:SelectionJourney,sourceId:number):NextTask[]{
 if(!validateJourney(j)||!j.reviewed)return []
 const actions={mention:'대상 이름·서비스와 질문의 관계를 공식 자료에서 확인합니다. 미언급 원인을 확정하지 않습니다.',recommendation:'질문 조건과 추천 후보의 근거를 비교하고, 고객 대상이 제외된 이유와 부족한 정보를 확인합니다.',accuracy:'답변의 사업·제품 정보를 고객이 확인한 사실 및 공식 자료와 대조합니다. 확인된 불일치만 수정 대상으로 정합니다.',connection:'답변 링크와 고객의 공식 홈페이지·판매처·신청 경로를 대조하고, 소유 관계 및 실제 이용 가능 여부를 확인합니다.'}
 return Object.entries(selectionCriteria).flatMap(([criterion,label])=>{const key=criterion as keyof typeof selectionCriteria,links=j.steps.flatMap((s,index)=>s.verdicts[key].value===true?[]:[{historyId:sourceId,stepIndex:index,criterion:key}]);if(!links.length)return [];const reason=links.map(x=>{const s=j.steps[x.stepIndex],v=s.verdicts[key];return `${x.stepIndex+1}단계 ${journeyStages[s.stage]} · 질문: ${s.question} · ${v.value===null?'판단 보류':'미확인·부적합'} · 근거: ${v.evidence||'추가 근거 필요'}`}).join('\n');return [{id:`${sourceId}-selection-${key}`,title:`${j.target} · ${label} 검토`,reason,action:actions[key],expected:`${label}의 판정 근거를 확보하고 실제 확인된 부족 정보만 보강합니다.`,remeasure:`같은 대상·채널·질문 순서·측정 조건으로 새 대화를 기록하고 ${label}의 변화를 비교합니다.`,selectionLinks:links,selectionKey:JSON.stringify([j.target,j.channel,j.conditions,j.steps.map(s=>[s.stage,s.question]),key,...(j.goalSnapshot?[j.goalSnapshot]:[])]),status:'pending',draft:'',application:'',appliedAt:null,measurementIds:[],outcome:'',updatedAt:new Date().toISOString()} as NextTask]})
}
export function comparableJourney(before:any,after:any,appliedAt:string){const a=before?.observed?.[0],b=after?.observed?.[0];return validateJourney(a)&&a.reviewed&&validateJourney(b)&&b.reviewed&&Number.isFinite(Date.parse(appliedAt))&&Number.isFinite(Date.parse(after.created_at))&&Date.parse(after.created_at)>Date.parse(appliedAt)&&sameGoalSnapshot(a.goalSnapshot||null,b.goalSnapshot||null)&&a.target===b.target&&a.channel===b.channel&&a.conditions===b.conditions&&JSON.stringify(a.steps.map(s=>[s.stage,s.question]))===JSON.stringify(b.steps.map(s=>[s.stage,s.question]))}
export function journeyComparison(before:any,after:any){const a=before.observed[0] as SelectionJourney,b=after.observed[0] as SelectionJourney;const label=(v:boolean|null)=>v===null?'판단 보류':v?'확인':'미확인·부적합';return `대상: ${a.target} · ${a.channel}\n기준 기록 #${before.id} → 후속 기록 #${after.id} · ${after.created_at}\n`+a.steps.map((s,i)=>`${i+1}. ${s.question}\n`+Object.entries(selectionCriteria).map(([k,l])=>{const key=k as keyof typeof selectionCriteria;return `${l}: ${label(s.verdicts[key].value)} → ${label(b.steps[i].verdicts[key].value)} · 후속 근거: ${b.steps[i].verdicts[key].evidence.slice(0,500)||'부족'}`}).join('\n')).join('\n\n')+'\n같은 조건의 기록 비교이며 단일 대화의 변화로 작업 효과나 매출·전환을 확정하지 않습니다.'}
