export const journeyStages={discovery:'처음 추천',evaluation:'알고 있는 대상 검토',fit:'조건 적합성',comparison:'대안 비교',conversion:'구매·신청 경로'}
export const selectionCriteria={mention:'업체·브랜드 언급',recommendation:'추천 후보 포함',accuracy:'핵심 정보 정확성',connection:'고객 홈페이지·판매처 연결'}
export type Verdict={value:boolean|null;evidence:string}
export type JourneyStep={stage:keyof typeof journeyStages;question:string;answer:string;urls:string[];verdicts:Record<keyof typeof selectionCriteria,Verdict>}
export type SelectionJourney={version:1;target:string;channel:string;conditions:string;steps:JourneyStep[];reviewed:boolean}
export const journeyChannels=['ChatGPT','Google AI','Naver AI Briefing','Naver AI Shopping','Gemini App','Perplexity','Claude','Copilot','OpenAI API','Gemini API']
export function validateJourney(x:any):x is SelectionJourney{
 if(!x||JSON.stringify(x).length>60000||x.version!==1||!journeyChannels.includes(x.channel)||typeof x.target!=='string'||!x.target.trim()||x.target.length>200||typeof x.conditions!=='string'||x.conditions.length>3000||typeof x.reviewed!=='boolean'||!Array.isArray(x.steps)||!x.steps.length||x.steps.length>6)return false
 return x.steps.every((s:any)=>s&&Object.prototype.hasOwnProperty.call(journeyStages,s.stage)&&typeof s.question==='string'&&!!s.question.trim()&&s.question.length<=2000&&typeof s.answer==='string'&&!!s.answer.trim()&&s.answer.length<=20000&&Array.isArray(s.urls)&&s.urls.length<=20&&s.urls.every((u:any)=>{try{const p=new URL(typeof u==='string'?u:'invalid');return ['http:','https:'].includes(p.protocol)&&!p.username&&!p.password}catch{return false}})&&Object.keys(selectionCriteria).every(k=>{const v=s.verdicts?.[k];return v&&(v.value===null||typeof v.value==='boolean')&&typeof v.evidence==='string'&&v.evidence.length<=2000&&(v.value===null||!!v.evidence.trim())&&(k==='accuracy'||v.value!==true||s.answer.includes(v.evidence))}))
}
export function journeyTransitions(j:SelectionJourney){return j.steps.slice(1).flatMap((step,i)=>Object.entries(selectionCriteria).flatMap(([key,label])=>{const k=key as keyof typeof selectionCriteria,previous=j.steps[i].verdicts[k],current=step.verdicts[k];if(previous.value===null||current.value===null||previous.value===current.value)return [];return [`${i+1} → ${i+2} 단계 · ${label}: ${previous.value?'확인':'미확인·부적합'} → ${current.value?'확인':'미확인·부적합'}`]}))}
export function journeySummary(j:SelectionJourney){return `대상: ${j.target} · 측정 채널: ${j.channel}\n측정 조건: ${j.conditions||'추가 조건 미기록'}\n`+j.steps.map((s,i)=>`${i+1}. ${journeyStages[s.stage]} · ${s.question}\n`+Object.entries(selectionCriteria).map(([k,label])=>{const v=s.verdicts[k as keyof typeof selectionCriteria];return `${label}: ${v.value===null?'판단 보류':v.value?'확인':'미확인·부적합'} · 근거: ${v.evidence.slice(0,500)||'부족'}`}).join('\n')).join('\n\n')+(journeyTransitions(j).length?'\n[대화 단계별 변화]\n'+journeyTransitions(j).join('\n'):'')+'\n직원이 검토한 단일 대화 관찰입니다. 노출 순위·구매 전환·작업 효과를 증명하지 않습니다.'}
export function journeyQuestions(target:string):JourneyStep[]{return [{stage:'evaluation',question:`${target} 어때?`},{stage:'fit',question:'내 이용 목적과 예산에 맞을까? 필요한 조건을 알려줘.'},{stage:'comparison',question:'다른 선택지와 비교하면 어떤 차이가 있어?'},{stage:'conversion',question:'어디에서 구매하거나 신청할 수 있어? 공식 경로를 알려줘.'}].map(x=>({...x,stage:x.stage as JourneyStep['stage'],answer:'',urls:[],verdicts:Object.fromEntries(Object.keys(selectionCriteria).map(k=>[k,{value:null,evidence:''}])) as JourneyStep['verdicts']}))}
