const assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),vm=require('vm')
function load(file,req=require){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,require:req,JSON,Object,Array,Date});return m.exports}
const c=load('src/lib/discovery/contextVersion.ts'),e=load('src/lib/discovery/evidence.ts')
const before=c.contextVersion(1,{goal:{area:'Seoul',service:'delivery'},questions:[{id:3,question:'original'}],facts:[]})
const reordered=c.contextVersion(1,{goal:{service:'delivery',area:'Seoul'},questions:[{id:3,question:'original'}],facts:[]})
assert.equal(c.contextImpact([before],reordered).status,'current')
const changed=c.contextVersion(1,{goal:{area:'Busan',service:'delivery'},questions:[{id:3,question:'original'}],facts:[]})
assert.equal(c.contextImpact([before],changed).status,'changed');assert.equal(c.contextImpact([before],changed).changed.join(','),'goal')
const qchanged=c.contextVersion(1,{goal:{area:'Seoul',service:'delivery'},questions:[{id:3,question:'edited'},{id:4,question:'new'}],facts:[]});assert.equal(c.contextImpact([before],qchanged).changedQuestions.join(','),'3,4')
assert.equal(c.contextImpact([],changed).status,'unknown');assert.equal(c.contextImpact([before],c.contextVersion(2,{goal:{}})).status,'unknown')
const raw={question:'original',measurements:[{result_text:'unaltered'}]},saved=e.attachWorkflow([raw,before],{kind:'improvement-workflow',workflow:{revision:1}})
assert.equal(saved.length,3);assert.equal(saved[1].kind,'analysis-context');assert.equal(e.originalEvidence(saved).length,1);assert.equal(e.originalEvidence(saved)[0].measurements[0].result_text,'unaltered')
const withRun=e.attachWorkflow([...saved,{kind:'engine-runs',revision:1,runs:[{status:'completed'}]}],{kind:'improvement-workflow',workflow:{revision:2}});assert.equal(withRun.filter(x=>x.kind==='engine-runs').length,1);assert.equal(e.originalEvidence(withRun).length,1)
console.log('Passed: stable context hashes, scoped change detection, legacy/cross-project uncertainty and snapshot preservation outside raw evidence')
