const assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),vm=require('vm')
function load(path,req){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,require:req||require,Request,JSON,Date,Number,Error,process:{env:{NEXT_PUBLIC_SUPABASE_URL:'url',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'pub',SUPABASE_SERVICE_ROLE_KEY:'key'}}});return m.exports}
let auth=true,changed=false,calls=0,failCAS=false
let row={id:10,measurement_round:'Day 0',observed:[{question:'original',measurements:[]}]}
const db={auth:{getUser:async()=>({data:{user:auth?{}:null}})},from(){let patch=null,insert=false;const q={select(){return q},eq(){return q},in(){return q},is(){return q},update(x){patch=x;return q},insert(){insert=true;return q},single:async()=>({data:insert?{id:99}:row}),maybeSingle:async()=>{if(failCAS)return {data:null};if(patch)row={...row,...patch};return {data:{id:row.id}}}};return q}}
const json=(body,status=200)=>({ok:status<400,status,json:async()=>body})
const route=load('src/app/api/discovery/reexecute/route.ts',n=>n==='next/server'?{NextResponse:{json:(b,o)=>json(b,o?.status||200)}}:n==='next/headers'?{cookies:()=>({get:()=>({value:'token'})})}:n==='@supabase/supabase-js'?{createClient:()=>db}:n.includes('contextStore')?{projectContext:async()=>({parts:{goal:'a'}})}:n.includes('contextVersion')?{contextImpact:()=>({changed:changed?['questions']:[]})}:n.includes('reexecution')?load('src/lib/discovery/reexecution.ts'):n.includes('improvement-workflow')?{POST:async()=>json({ok:true})}:{POST:async()=>{calls++;return json({measurementRound:'Day 0',observed:[],analysis:'new analysis'})}})
const post=b=>route.POST(new Request('https://example.com/api/discovery/reexecute',{method:'POST',body:JSON.stringify({projectId:1,sourceId:10,...b})}))
;(async()=>{auth=false;assert.equal((await post()).status,401);auth=true;changed=true;assert.equal((await post()).status,409);assert.equal(calls,0);changed=false;failCAS=true;assert.equal((await post()).status,409);assert.equal(calls,0);failCAS=false;assert.equal((await post()).status,200);assert.equal(calls,1);assert.equal(row.observed[0].question,'original');assert.equal(row.observed[1].runs[0].status,'completed');assert.equal((await post()).status,200);assert.equal(calls,1);row.observed[1].runs[0].status='running';assert.equal((await post()).status,409);assert.equal(calls,1);console.log('Passed: authenticated scoped rerun, changed-question gate, CAS before model call, source preservation and completed/running duplicate isolation')})().catch(e=>{console.error(e);process.exitCode=1})
