const assert=require('node:assert/strict'),ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm')
function load(path){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,JSON,Number,Error,Date,Set,URL});return m.exports}
const w=load('src/lib/workPlan.ts'),a=load('src/lib/channelAssets.ts'),work={name:'고객 질문 블로그',channel:'공식 블로그',quantity:2,unit:'건',reason:'확인된 이용 조건 설명 보완',deliverable:'실제 질문에 답하는 글 2건',completion:'승인 문구 게시 및 URL 기록'}
assert(w.validAdditionalWork(work));assert(!w.validAdditionalWork({...work,quantity:0}));assert(!w.validAdditionalWork({...work,quantity:101}));assert.throws(()=>w.parseWorkPlan('일반 텍스트'));assert.equal(w.parseWorkPlan(JSON.stringify({draft:'수정안',assessment:{status:'needs_evidence',reason:'소유 미확인'},additionalWork:work})).additionalWork,null)
assert(w.parseWorkPlan(JSON.stringify({draft:'수정안',assessment:{status:'ready',reason:'필요 정보 확인'},additionalWork:work})).additionalWork)
const before={observed:[{query:'업체 추천',checkedAt:'2026-10-01',results:[{channel:'블로그',items:[{link:'https://example.com/old'}]}]}]},after={observed:[{query:'업체 추천',checkedAt:'2026-10-04',results:[{channel:'블로그',items:[{link:'https://example.com/new'}]}]}]}
assert(w.naverComparable(before,after,'2026-10-03'));assert(!w.naverComparable(before,after,'2026-10-05'));assert(!w.naverComparable(before,{observed:[{...after.observed[0],query:'다른 검색어'}]},'2026-10-03'));assert(!w.naverComparable(before,{observed:[{...after.observed[0],results:[{channel:'블로그',error:'API 오류'}]}]},'2026-10-03'));assert(!w.naverComparable({observed:[{...before.observed[0],results:[]}]},after,'2026-10-03'));assert(w.naverOutcome(before,after).includes('신규 출처 1건'))
assert(a.validAssets([{type:'blog',url:'https://blog.naver.com/example',ownership:'unconfirmed',note:'고객 확인 전'}]));assert(!a.validAssets([{type:'blog',url:'javascript:alert(1)',ownership:'confirmed',note:''}]));assert(!a.validAssets([{type:'blog',url:'https://name:password@example.com',ownership:'confirmed',note:''}]))
console.log('Passed: work assessment gates, bounded quote candidates, matching Naver query/channels/time and explicit channel ownership')
