import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
import {requireStaff} from '../../../lib/requireStaff'
export const dynamic='force-dynamic'
export const revalidate=0
const labels:Record<string,string>={diagnosis_pending:'진단 대기',reviewing:'진단·검토 중',proposal:'진행 협의',customer_delivery:'고객 전달',quote_drafting:'견적 작성 중',quote_ready:'견적 작성 완료',quote_sent:'견적 전달 완료',contracted:'계약 완료',converted:'프로젝트 전환',closed:'상담 종료'}
type Inquiry={id:number;company_name:string;website_url:string;status:string;project_id:number|null;created_at:string}
export default async function InquiryList({searchParams}:{searchParams?:{stage?:string;q?:string}}){
 await requireStaff()
 const stage=['pending','contracted','closed'].includes(searchParams?.stage||'')?searchParams!.stage!:'all',q=(searchParams?.q||'').trim().slice(0,100)
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY
 let rows:Inquiry[]=[],error=false
 if(url&&key){const s=createClient(url,key,{global:{fetch:(input,init)=>fetch(input,{...init,cache:'no-store'})}});let query=s.from('discovery_inquiries').select('id,company_name,website_url,status,project_id,created_at').order('created_at',{ascending:false});if(q)query=query.ilike('company_name',`%${q.replace(/[\\%_]/g,'\\$&')}%`);const result=await query.limit(200);rows=result.data||[];error=!!result.error}else error=true
 const filtered=rows.filter(row=>stage==='all'||(stage==='pending'?!row.project_id&&row.status!=='closed':stage==='contracted'?!!row.project_id:!row.project_id&&row.status==='closed'))
 return <main className="min-h-screen bg-[#F4F7F6] px-5 pb-12 pt-24 text-[#0A0F1E] md:px-8"><div className="mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#087A56]">Consultation List</p><h1 className="mt-2 text-3xl font-extrabold">상담 신청 업체 목록</h1><p className="mt-3 text-sm text-gray-600">접수된 업체를 선택해 초기 진단과 보고서를 확인합니다. 계약된 업체는 연결된 관리 프로젝트에서 후속 업무를 진행합니다.</p></div><Link href="/discovery" className="rounded-xl border bg-white px-5 py-3 text-sm font-bold">← 회사 대시보드</Link></header><section className="rounded-2xl border bg-white p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><nav aria-label="상담 상태" className="flex flex-wrap gap-2">{[['all','전체 상담'],['pending','계약 전 상담'],['contracted','계약된 상담'],['closed','미계약 종료']].map(([value,label])=><Link key={value} href={`/discovery/inquiries?${new URLSearchParams({stage:value,...(q?{q}:{})})}`} className={'rounded-lg border px-3 py-2 text-sm font-bold '+(stage===value?'border-emerald-400 bg-emerald-50 text-[#087A56]':'border-gray-200')}>{label}</Link>)}</nav><Link href="/ai-search/consulting?topic=naver" className="text-sm font-bold text-[#087A56]">신규 업체 상담 신청 폼 →</Link></div><form className="mt-5 flex gap-2" action="/discovery/inquiries"><input type="hidden" name="stage" value={stage}/><input aria-label="업체명 검색" name="q" defaultValue={q} maxLength={100} placeholder="상담 신청 업체명 검색" className="min-w-0 flex-1 rounded-xl border px-4 py-3 text-sm"/><button className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">검색</button></form>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">상담 목록을 불러오지 못했습니다. 다시 확인해 주세요.</p>}<div className="mt-5 space-y-3">{filtered.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><h2 className="font-extrabold">{row.company_name}</h2><p className="mt-1 break-all text-xs text-gray-500">{row.website_url}</p><p className="mt-2 text-xs text-gray-500">{labels[row.status]||row.status} · 접수 {new Date(row.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</p></div><div className="flex flex-wrap gap-2"><Link href={`/discovery/inquiries/${row.id}`} className="rounded-lg bg-[#087A56] px-4 py-2 text-sm font-bold text-white">{row.project_id?'상담 자료 보기':'업체 선택 · 사전 진단'}</Link>{row.project_id&&<Link href={`/discovery/projects/${row.project_id}`} className="rounded-lg border px-4 py-2 text-sm font-bold">관리 프로젝트 →</Link>}</div></article>)}{!filtered.length&&!error&&<p className="rounded-xl bg-gray-50 p-5 text-sm text-gray-500">이 조건에 해당하는 상담 신청 업체가 없습니다. 전체 상담을 선택하거나 검색어를 확인해 주세요.</p>}</div><p className="mt-4 text-xs text-gray-400">최근 접수한 상담 최대 200건을 표시합니다.</p></section></div></main>
}
