'use client'
import SearchGoalFields from '../../../../components/SearchGoalFields'
import {emptySearchGoal} from '../../../../lib/engagement'
import {useEffect,useState} from 'react'
import {useRouter,useSearchParams} from 'next/navigation'
export default function StaffInquiryForm(){
 const [searchGoal,setSearchGoal]=useState({...emptySearchGoal,channels:['AI']})
 const searchParams=useSearchParams(),[transfer,setTransfer]=useState<{token:string;website:string;checkedAt:string;pageCount:number}|null>(null)
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[values,setValues]=useState({company_name:'',website_url:'',contact_name:'',phone:'',email:'',industry:'',main_services:'',message:'',ai:true,naver:false})
 useEffect(()=>{if(searchParams.get('from')!=='website')return;try{const raw=sessionStorage.getItem('damda-website-transfer');if(!raw)return;const data=JSON.parse(raw);if(typeof data.token!=='string'||typeof data.website!=='string')return;setTransfer(data);setValues(old=>({...old,website_url:data.website}))}catch{setError('이전 확인 자료를 불러오지 못했습니다. 홈페이지 주소를 입력해 등록할 수 있습니다.')}},[searchParams])
 const fields=[['company_name','업체명 *'],['website_url','홈페이지 *'],['contact_name','담당자 *'],['industry','업종'],['main_services','주요 서비스·상품'],['phone','전화번호 (선택)'],['email','이메일 (선택)'],['message','상담 내용']] as const
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/discovery/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,...(searchGoal.service.trim()&&searchGoal.situation.trim()?{search_goal:searchGoal}:{}),...(transfer?{websiteTransfer:transfer.token}:{})})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(transfer)sessionStorage.removeItem('damda-website-transfer');router.push(`/discovery/inquiries/${d.id}`)}catch(e){setError(e instanceof Error?e.message:'등록 실패');setBusy(false)}}
 return <form onSubmit={submit} className="mt-6 rounded-2xl border bg-white p-6">{transfer&&<div className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm"><p className="font-bold">홈페이지 확인 자료 연결됨 · {transfer.pageCount}개 페이지</p><p className="mt-2 break-all text-xs">{transfer.website} · {new Date(transfer.checkedAt).toLocaleString('ko-KR')}</p><p className="mt-2 text-xs">상담 등록 시 이 자료를 함께 저장합니다. 다른 홈페이지를 등록하려면 자료 연결을 해제하세요.</p><button disabled={busy} type="button" onClick={()=>{setTransfer(null);sessionStorage.removeItem('damda-website-transfer')}} className="mt-2 text-xs font-bold underline">자료 연결 해제</button></div>}<fieldset disabled={busy}><div className="grid gap-4 md:grid-cols-2">{fields.map(([k,l])=><label key={k} className="text-sm font-bold">{l}<input required={['company_name','website_url','contact_name'].includes(k)} disabled={k==='website_url'&&!!transfer} maxLength={2000} type={k==='email'?'email':'text'} value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>)}</div><div className="mt-5"><SearchGoalFields value={searchGoal} onChange={g=>{setSearchGoal(g);setValues(v=>({...v,ai:g.channels.includes('AI'),naver:g.channels.includes('Naver')}))}}/></div><p className="mt-5 text-sm font-bold">상담 범위</p><div className="mt-3 flex gap-5"><label className="text-sm"><input type="checkbox" checked={values.ai} onChange={e=>setValues({...values,ai:e.target.checked})}/> 검색·AI 진단</label><label className="text-sm"><input type="checkbox" checked={values.naver} onChange={e=>setValues({...values,naver:e.target.checked})}/> 네이버 진단</label></div><p className="mt-4 text-xs leading-5 text-gray-500">직원 등록은 고객용 휴대전화 인증 없이 진행합니다. 고객이 직접 동의하거나 인증한 접수로 기록하지 않으며, 연락처는 필요한 경우에만 입력하세요.</p><button disabled={busy||(!values.ai&&!values.naver)} className="mt-5 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'등록 중…':'상담 등록·진단 시작'}</button></fieldset>{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}</form>
}
