import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import QuestionGenerator from './QuestionGenerator'
import SavedQuestions from './SavedQuestions'
export const dynamic='force-dynamic'
type Dimension={id:number;dimension_type:string;dimension_value:string;priority:number;is_active:boolean}
type Question={id:number;question:string;intent:string|null;dimension_count:number;is_benchmark:boolean;status:string;created_at:string}
async function getData(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return{dimensions:[] as Dimension[],questions:[] as Question[],error:'Supabase 서버 환경변수를 확인해 주세요.'};const s=createClient(url,key,{auth:{persistSession:false}});const[d,q]=await Promise.all([s.from('discovery_question_dimensions').select('id,dimension_type,dimension_value,priority,is_active').eq('project_id',1).eq('is_active',true).order('priority',{ascending:false}),s.from('discovery_questions').select('id,question,intent,dimension_count,is_benchmark,status,created_at',{count:'exact'}).eq('project_id',1).order('created_at',{ascending:false})]);return{dimensions:(d.data??[]) as Dimension[],questions:(q.data??[]) as Question[],error:d.error?.message??q.error?.message??null}}
export default async function QuestionsPage(){const{dimensions,questions,error}=await getData();return <div className="min-h-screen bg-[#F4F7F6] text-[#0A0F1E]"><div className="mx-auto max-w-7xl px-5 pb-10 pt-24 md:px-8"><header className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.22em] text-[#0A9B6C]">Question Engine</p><h1 className="text-3xl font-extrabold md:text-4xl">질문 생성 · Benchmark</h1><p className="mt-2 text-sm text-gray-500">질문을 생성·저장하고, 반복 측정할 기준 질문을 지정합니다.</p></div><div className="flex gap-2"><Link href="/discovery/dimensions" className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-bold shadow-sm">질문 재료</Link><Link href="/discovery/projects/1" className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-bold shadow-sm">← 프로젝트 대시보드</Link></div></header>{error?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>:<div className="space-y-6"><QuestionGenerator dimensions={dimensions} projectId={1}/><SavedQuestions initial={questions} projectId={1} projectName="주식회사 더담다"/></div>}</div></div>}
