'use client'
import {useEffect,useState} from 'react'
import {reviewLabels} from '../../../lib/questionReview'
export default function QuestionReviewHistory({projectId}:{projectId:number}){
 const[rows,setRows]=useState<any[]>([]),[error,setError]=useState('')
 async function reload(){try{const r=await fetch('/api/discovery/review-questions?projectId='+projectId,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.history);setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{reload();const changed=()=>reload();window.addEventListener('discovery-review-changed',changed);return()=>window.removeEventListener('discovery-review-changed',changed)},[projectId])
 return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">질문 검토·선택 이력</h2><p className="mt-2 text-sm text-gray-500">최근 30회 · 당시 고객 목표와 AI 의견, 직원 선택을 보존합니다. 미선택은 제외 확정과 구분합니다.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<button onClick={reload} className="mt-3 rounded-lg border px-3 py-2 text-sm">이력 새로고침</button>{!rows.length&&!error&&<p className="mt-3 text-sm">아직 저장된 검토가 없습니다.</p>}{rows.map(row=><details key={row.id} className="mt-4 rounded-xl border p-4"><summary className="cursor-pointer font-bold">{new Date(row.created_at).toLocaleString('ko-KR')} · {row.finalized_at?'직원 선택 저장 완료':'AI 검토 완료 · 선택 대기'}</summary><p className="mt-3 text-sm">당시 목표: {row.goal_snapshot?.searchGoal?.service||'목표 미등록'} · {row.goal_snapshot?.searchGoal?.situation||'서비스 기준 검토'}{row.goal_snapshot?.goalId?' · 목표 #'+row.goal_snapshot.goalId:''}</p>{row.parent_review_id&&<p className="mt-2 text-xs text-gray-500">이전 검토를 수정·재검토한 이력입니다.</p>}{row.candidates.map((c:any)=>{const review=row.reviews.find((r:any)=>r.key===c.key),decision=row.staff_decisions?.find((r:any)=>r.key===c.key);return <div key={c.key} className="mt-3 border-t pt-3 text-sm"><p className="font-bold">{c.question}</p><p className="mt-1">AI: {reviewLabels[review?.decision as keyof typeof reviewLabels]||'검토 없음'} · {review?.reason}</p><p className="mt-1">직원: {decision?decision.selected?'저장 선택':'미선택':'선택 대기'}{decision?.reason?' · '+decision.reason:''}</p></div>})}</details>)}</section>
}
