'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
type D={id:number;dimension_type:string;dimension_value:string;priority:number}
type C={question:string;intent:string;mode:string;ingredients:D[];combinationKey:string}
export default function QuestionGenerator({dimensions,projectId}:{dimensions:D[];projectId:number}){const router=useRouter();const[count,setCount]=useState(12),[cs,setCs]=useState<C[]>([]),[sel,setSel]=useState<Set<string>>(new Set()),[saving,setSaving]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');const run=async()=>{setBusy(true);setMsg('');try{const response=await fetch('/api/discovery/generate-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,count})});const data=await response.json();if(!response.ok)throw new Error(data.error||'질문 생성 실패');const generated:C[]=data.questions;setCs(generated);setSel(new Set());setMsg(generated.length?'':dimensions.length<2?'질문을 만들려면 서로 다른 질문 재료가 최소 2개 필요합니다.':'현재 재료에서 조합 가능한 질문이 없습니다. SERVICE 등의 재료를 확인해 주세요.')}catch(e:any){setCs([]);setMsg(e.message||'질문을 만들지 못했습니다.')}finally{setBusy(false)}};const toggle=(k:string)=>{const n=new Set(sel);n.has(k)?n.delete(k):n.add(k);setSel(n)}
 const save=async()=>{const chosen=cs.filter(c=>sel.has(c.combinationKey));if(!chosen.length)return;setSaving(true);setMsg('');try{const response=await fetch('/api/discovery/saved-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,questions:chosen.map(c=>({question:c.question,intent:c.intent,ingredientIds:c.ingredients.map(x=>x.id)}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'저장 실패');setMsg(data.saved+'개 질문을 저장했습니다.'+(data.skipped?' 이미 저장된 '+data.skipped+'개는 건너뛰었습니다.':''));setSel(new Set());router.refresh()}catch(e:any){setMsg('저장 실패: '+e.message)}finally{setSaving(false)}}
 return <div className="space-y-6"><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Question Engine</p><h2 className="mt-1 text-2xl font-extrabold">질문 후보 생성</h2><p className="mt-2 text-sm text-gray-500">검토한 재료로 질문을 만든 뒤 필요한 후보를 골라 저장합니다.</p></div><div className="flex items-center gap-2"><label className="text-sm text-gray-500">후보 수</label><select value={count} onChange={e=>setCount(Number(e.target.value))} className="rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm font-bold">{[6,12,18,24].map(n=><option key={n}>{n}</option>)}</select><button onClick={run} disabled={busy} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'질문 생성 중...':'질문 생성'}</button></div></div></section>
 {msg&&cs.length===0&&<p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{msg}</p>}
 {cs.length>0&&<section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">생성 결과</h2><p className="mt-1 text-sm text-gray-400">{cs.length}개 후보 · {sel.size}개 선택</p></div><button onClick={save} disabled={sel.size===0||saving} className="rounded-xl bg-[#0A0F1E] px-4 py-2 text-sm font-bold text-white disabled:bg-gray-200 disabled:text-gray-400">{saving?'저장 중...':sel.size+'개 질문 저장'}</button></div>{msg&&<div className={"mb-4 rounded-xl border p-3 text-sm "+(msg.startsWith('저장 실패')?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700')}>{msg}</div>}<div className="space-y-3">{cs.map((c,i)=><article key={c.combinationKey} onClick={()=>toggle(c.combinationKey)} className={'cursor-pointer rounded-xl border p-4 '+(sel.has(c.combinationKey)?'border-[#0A9B6C] bg-[#F0FBF7]':'border-gray-200 bg-[#FAFBFB]')}><div className="flex gap-3"><div className={'mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded border text-xs '+(sel.has(c.combinationKey)?'border-[#0A9B6C] bg-[#0A9B6C] text-white':'border-gray-300')}>{sel.has(c.combinationKey)?'✓':''}</div><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-gray-400">Q{i+1}</span><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-[#087A56]">{c.mode}</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-800">{c.intent}</span><span className="text-[10px] text-gray-400">{c.ingredients.length} dimensions</span></div><p className="mt-2 font-bold leading-relaxed">{c.question}</p><div className="mt-3 flex flex-wrap gap-2">{c.ingredients.map(x=><span key={x.id} className="rounded-full bg-white px-2 py-1 text-[10px] text-gray-500"><b>{x.dimension_type}</b> · {x.dimension_value}</span>)}</div></div></div></article>)}</div></section>}</div>}
