'use client'
import {useState} from 'react'
import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
type Q={id:number;question:string;intent:string|null;dimension_count:number;is_benchmark:boolean;status:string;created_at:string}
export default function SavedQuestions({initial}:{initial:Q[]}){
 const[qs,setQs]=useState(initial),[busy,setBusy]=useState<number|null>(null),[msg,setMsg]=useState('')
 const toggle=async(q:Q)=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return;setBusy(q.id);setMsg('');const supabase=createClient(url,key);const next=!q.is_benchmark;const{error}=await supabase.from('discovery_questions').update({is_benchmark:next}).eq('id',q.id).eq('project_id',1);setBusy(null);if(error){setMsg('변경 실패: '+error.message);return}setQs(x=>x.map(v=>v.id===q.id?{...v,is_benchmark:next}:v));setMsg(next?'Benchmark로 지정했습니다.':'Benchmark 지정을 해제했습니다.')}
 const n=qs.filter(q=>q.is_benchmark).length
 return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Saved Questions</p><h2 className="mt-1 text-2xl font-extrabold">저장된 질문 / Benchmark</h2><p className="mt-2 text-sm text-gray-500">저장 {qs.length}개 · Benchmark {n}개 · 기준 질문은 앞으로 같은 문장으로 반복 측정합니다.</p></div>{msg&&<div className={"mb-4 rounded-xl border p-3 text-sm "+(msg.startsWith('변경 실패')?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700')}>{msg}</div>}{qs.length===0?<div className="rounded-xl border border-dashed border-gray-200 p-8 text-center text-sm text-gray-400">아직 저장된 질문이 없습니다.</div>:<div className="space-y-3">{qs.map((q,i)=><article key={q.id} className={'rounded-xl border p-4 '+(q.is_benchmark?'border-[#0A9B6C] bg-[#F0FBF7]':'border-gray-200 bg-[#FAFBFB]')}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap gap-2 text-[10px]"><span className="font-bold text-gray-400">Q{i+1}</span>{q.intent&&<span className="rounded-full bg-white px-2 py-1 text-gray-500">{q.intent}</span>}<span className="rounded-full bg-white px-2 py-1 text-gray-500">{q.dimension_count} dimensions</span>{q.is_benchmark&&<span className="rounded-full bg-[#0A9B6C] px-2 py-1 font-bold text-white">BENCHMARK</span>}</div><p className="font-bold leading-relaxed">{q.question}</p></div><button onClick={()=>toggle(q)} disabled={busy===q.id} className={'shrink-0 rounded-xl px-4 py-2 text-sm font-bold '+(q.is_benchmark?'border border-gray-200 bg-white text-gray-700':'bg-[#0A0F1E] text-white')}>{busy===q.id?'변경 중...':q.is_benchmark?'Benchmark 해제':'Benchmark 지정'}</button>{q.is_benchmark&&<Link href={'/discovery/measurements?question='+q.id} className="shrink-0 rounded-xl bg-[#0A9B6C] px-4 py-2 text-center text-sm font-bold text-white">Day 0 측정</Link>}</div></article>)}</div>}</section>
}