'use client'
import {useState} from 'react'
import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
type Q={id:number;question:string;intent:string|null;dimension_count:number;is_benchmark:boolean;status:string;created_at:string}
type AutoChannel='gemini'|'openai'
export default function SavedQuestions({initial,projectId,projectName}:{initial:Q[];projectId:number;projectName:string}){
 const[qs,setQs]=useState(initial),[busy,setBusy]=useState<number|null>(null),[autoBusy,setAutoBusy]=useState<string|null>(null),[batchBusy,setBatchBusy]=useState(false),[msg,setMsg]=useState('')
 const toggle=async(q:Q)=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return;setBusy(q.id);setMsg('');const supabase=createClient(url,key);const next=!q.is_benchmark;const{error}=await supabase.from('discovery_questions').update({is_benchmark:next}).eq('id',q.id).eq('project_id',projectId);setBusy(null);if(error){setMsg('변경 실패: '+error.message);return}setQs(x=>x.map(v=>v.id===q.id?{...v,is_benchmark:next}:v));setMsg(next?'Benchmark로 지정했습니다.':'Benchmark 지정을 해제했습니다.')}
 const requestMeasure=async(q:Q,channel:AutoChannel)=>{const r=await fetch('/api/discovery/measure-'+channel,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,questionId:q.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'자동 측정 실패');if(channel==='openai'&&(!j.verified||!j.measurementId))throw new Error('DB 저장 검증에 실패했습니다.');return j}
 const autoMeasure=async(q:Q,channel:AutoChannel)=>{const label=channel==='openai'?'OpenAI Web Search':'Gemini';const key=channel+'-'+q.id;setAutoBusy(key);setMsg('');try{const j=await requestMeasure(q,channel);setMsg(label+' 자동 측정 완료 · '+(j.discovered?projectName+' 발견':projectName+' 미발견')+' · 대시보드와 캘린더에 저장되었습니다.')}catch(e:any){setMsg(label+' 자동 측정 실패: '+e.message)}finally{setAutoBusy(null)}}
 const runAllOpenAI=async()=>{const targets=qs.filter(q=>q.is_benchmark);if(!targets.length){setMsg('실패: 먼저 Benchmark 질문을 지정해 주세요.');return}setBatchBusy(true);setMsg(`OpenAI 전체 측정 시작 · Benchmark ${targets.length}개를 순서대로 측정합니다.`);let ok=0,discovered=0,reused=0;const failures:string[]=[];for(let i=0;i<targets.length;i++){const q=targets[i];setMsg(`OpenAI 전체 측정 중 · ${i+1}/${targets.length} · Q${qs.indexOf(q)+1}`);try{const j=await requestMeasure(q,'openai');ok++;if(j.discovered)discovered++;if(j.reused)reused++}catch(e:any){failures.push(`Q${qs.indexOf(q)+1}: ${e.message}`)}}setBatchBusy(false);const newlySaved=ok-reused;setMsg(failures.length?`OpenAI 전체 측정 검증 완료 · DB 확인 ${ok}/${targets.length} · 신규 저장 ${newlySaved} · 기존 기록 재사용 ${reused} · 실패 ${failures.length}건 (${failures.join(' / ')})`:`OpenAI 전체 측정 검증 완료 · DB 확인 ${ok}/${targets.length} · 신규 저장 ${newlySaved} · 기존 기록 재사용 ${reused} · 발견 ${discovered}건. 이제 대시보드에서 확인할 수 있습니다.`)}
 const n=qs.filter(q=>q.is_benchmark).length
 return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Saved Questions</p><h2 className="mt-1 text-2xl font-extrabold">저장된 질문 / Benchmark</h2><p className="mt-2 text-sm text-gray-500">저장 {qs.length}개 · Benchmark {n}개 · 기준 질문은 앞으로 같은 문장으로 반복 측정합니다.</p></div><button onClick={runAllOpenAI} disabled={batchBusy||autoBusy!==null||n===0} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{batchBusy?'OpenAI 전체 측정 중...':`OpenAI Benchmark 전체 측정 (${n})`}</button></div>{msg&&<div className={"mb-4 rounded-xl border p-3 text-sm "+(msg.includes('실패')?'border-red-200 bg-red-50 text-red-700':msg.includes('측정 중')||msg.includes('측정 시작')?'border-blue-200 bg-blue-50 text-blue-700':'border-emerald-200 bg-emerald-50 text-emerald-700')}>{msg}</div>}{qs.length===0?<div className="rounded-xl border border-dashed border-gray-200 p-8 text-center text-sm text-gray-400">아직 저장된 질문이 없습니다.</div>:<div className="space-y-3">{qs.map((q,i)=><article key={q.id} className={'rounded-xl border p-4 '+(q.is_benchmark?'border-[#0A9B6C] bg-[#F0FBF7]':'border-gray-200 bg-[#FAFBFB]')}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap gap-2 text-[10px]"><span className="font-bold text-gray-400">Q{i+1}</span>{q.intent&&<span className="rounded-full bg-white px-2 py-1 text-gray-500">{q.intent}</span>}<span className="rounded-full bg-white px-2 py-1 text-gray-500">{q.dimension_count} dimensions</span>{q.is_benchmark&&<span className="rounded-full bg-[#0A9B6C] px-2 py-1 font-bold text-white">BENCHMARK</span>}</div><p className="font-bold leading-relaxed">{q.question}</p></div><button onClick={()=>toggle(q)} disabled={busy===q.id||batchBusy} className={'shrink-0 rounded-xl px-4 py-2 text-sm font-bold '+(q.is_benchmark?'border border-gray-200 bg-white text-gray-700':'bg-[#0A0F1E] text-white')}>{busy===q.id?'변경 중...':q.is_benchmark?'Benchmark 해제':'Benchmark 지정'}</button>{q.is_benchmark&&<><Link href={'/discovery/measurements?project='+projectId+'&question='+q.id} className="shrink-0 rounded-xl bg-[#0A9B6C] px-4 py-2 text-center text-sm font-bold text-white">Day 0 수동 측정</Link><button onClick={()=>autoMeasure(q,'gemini')} disabled={autoBusy!==null||batchBusy} className="shrink-0 rounded-xl border border-[#0A9B6C] bg-white px-4 py-2 text-sm font-bold text-[#087A56] disabled:opacity-50">{autoBusy==='gemini-'+q.id?'Gemini 측정 중...':'Gemini 자동 측정'}</button><button onClick={()=>autoMeasure(q,'openai')} disabled={autoBusy!==null||batchBusy} className="shrink-0 rounded-xl border border-[#0A0F1E] bg-white px-4 py-2 text-sm font-bold text-[#0A0F1E] disabled:opacity-50">{autoBusy==='openai-'+q.id?'OpenAI 측정 중...':'OpenAI 자동 측정'}</button></>}</div></article>)}</div>}</section>
}