'use client'
import {useEffect,useState} from 'react'
import type {ChannelAsset} from '../../lib/channelAssets'
const labels={website:'공식 홈페이지',blog:'블로그',place:'업체·지도 정보',store:'쇼핑몰·판매 페이지',social:'SNS',other:'기타 외부 근거'}
export default function ChannelAssets({projectId}:{projectId:number}){
 const[assets,setAssets]=useState<ChannelAsset[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{fetch('/api/discovery/channel-assets?projectId='+projectId,{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setAssets(j.assets)}).catch(e=>setMessage(e.message))},[projectId])
 function patch(i:number,p:Partial<ChannelAsset>){setAssets(old=>old.map((x,n)=>n===i?{...x,...p}:x))}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/discovery/channel-assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,assets})}),j=await r.json();if(!r.ok)throw Error(j.error);setMessage('고객 채널 정보를 저장했습니다. 다음 분석·초안 생성부터 반영됩니다.')}catch(e){setMessage(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}}
 return <details className="mb-6 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">고객 보유 채널 · 공식 계정 확인</summary><p className="mt-3 text-sm leading-6 text-gray-500">홈페이지·블로그·판매처를 등록하면 기존 콘텐츠를 먼저 검토하도록 분석에 연결됩니다. 검색 결과에 같은 이름이 있다는 이유만으로 소유 채널로 등록하지 마세요. 소유 확인은 고객 또는 담당자가 확인한 상태이며 플랫폼의 자동 인증이 아닙니다.</p><fieldset disabled={busy}>{assets.map((a,i)=><div key={i} className="mt-4 grid gap-3 rounded-lg border p-3 md:grid-cols-2"><label className="text-sm">종류<select value={a.type} onChange={e=>patch(i,{type:e.target.value as ChannelAsset['type']})} className="mt-1 w-full rounded border p-2">{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="text-sm">소유·관계 확인<select value={a.ownership} onChange={e=>patch(i,{ownership:e.target.value as ChannelAsset['ownership']})} className="mt-1 w-full rounded border p-2"><option value="unconfirmed">미확인 · 후보</option><option value="confirmed">담당자 확인</option></select></label><label className="text-sm md:col-span-2">공개 URL<input value={a.url} onChange={e=>patch(i,{url:e.target.value})} maxLength={1000} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm md:col-span-2">확인 근거·기존 운영 내용<input value={a.note} onChange={e=>patch(i,{note:e.target.value})} maxLength={1000} placeholder="예: 고객이 공식 블로그라고 확인 · 기존 이용 사례 글 운영" className="mt-1 w-full rounded border p-2"/></label><button onClick={()=>setAssets(old=>old.filter((_,n)=>n!==i))} className="text-left text-xs text-red-700">삭제</button></div>)}<div className="mt-4 flex gap-3"><button disabled={assets.length>=12} onClick={()=>setAssets(old=>[...old,{type:'blog',url:'',ownership:'unconfirmed',note:''}])} className="rounded border px-3 py-2 text-sm">채널 추가</button><button onClick={save} className="rounded bg-emerald-700 px-3 py-2 text-sm text-white">채널 정보 저장</button></div></fieldset>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</details>
}
