'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
type B={id:number;question:string}
export default function ProjectOnboarding({projectId,benchmarks,measurementCount}:{projectId:number;benchmarks:B[];measurementCount:number}){
 const router=useRouter(),[busy,setBusy]=useState(''),[msg,setMsg]=useState('')
 const generate=async()=>{setBusy('generate');setMsg('');try{const r=await fetch('/api/discovery/bootstrap-benchmarks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Benchmark 생성 실패');setMsg(`Benchmark ${j.count}개를 생성했습니다.`);router.refresh()}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 const measure=async()=>{setBusy('measure');setMsg('');let ok=0,found=0;const fail:string[]=[];for(let i=0;i<benchmarks.length;i++){setMsg(`OpenAI Day 0 측정 중 · ${i+1}/${benchmarks.length}`);try{const r=await fetch('/api/discovery/measure-openai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,questionId:benchmarks[i].id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'측정 실패');ok++;if(j.discovered)found++}catch(e:any){fail.push(`Q${i+1} ${e.message}`)}}setBusy('');setMsg(fail.length?`측정 완료 ${ok}/${benchmarks.length} · 실패 ${fail.length}건: ${fail.join(' / ')}`:`OpenAI Day 0 측정 완료 · ${ok}건 중 발견 ${found}건`);router.refresh()}
 const step=benchmarks.length===0?1:measurementCount===0?2:3
 return <section className="mb-8 rounded-2xl border border-emerald-200 bg-emerald-50/50 p-5 shadow-sm md:p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Project Start</p><h2 className="mt-1 text-xl font-extrabold">신규 프로젝트 시작</h2><p className="mt-2 text-sm text-gray-600">Benchmark를 확정하고 현재 상태를 먼저 측정한 뒤 개선 분석을 시작합니다.</p><div className="mt-5 grid gap-3 md:grid-cols-3">{[['1','Benchmark 생성',benchmarks.length?`${benchmarks.length}개 준비됨`:'고객 관점 기준 질문 만들기'],['2','Day 0 측정',measurementCount?`${measurementCount}건 기록됨`:'현재 발견 상태 기록'],['3','개선 분석','측정 후 진행','원인·개선과제 검토']].map((x,i)=><div key={x[0]} className={"rounded-xl border p-4 "+(step===i+1?'border-[#0A9B6C] bg-white':'border-gray-200 bg-white/60')}><p className="text-xs font-bold text-[#0A9B6C]">STEP {x[0]}</p><p className="mt-1 font-extrabold">{x[1]}</p><p className="mt-1 text-xs text-gray-500">{x[2]}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2">{benchmarks.length===0?<button onClick={generate} disabled={!!busy} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy==='generate'?'Benchmark 생성 중...':'Benchmark 자동 생성'}</button>:measurementCount===0?<button onClick={measure} disabled={!!busy} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy==='measure'?'Day 0 측정 중...':`OpenAI Day 0 전체 측정 (${benchmarks.length})`}</button>:<span className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#087A56]">기초 측정 완료 · 아래에서 Day 0 분석을 진행하세요.</span>}</div>{msg&&<p className="mt-4 rounded-xl border border-gray-200 bg-white p-3 text-sm text-gray-700">{msg}</p>}</section>
}