'use client'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {useState} from 'react'
import {Quotation,quoteStatuses,quoteTotals} from '../../lib/quotation'
export type QuoteRow={inquiryId:number;company:string;inquiryStatus:string;projectId:number|null;updatedAt:string;document:Quotation}
const money=(n:number)=>new Intl.NumberFormat('ko-KR').format(n)+'원'
export default function QuotationList({rows,error}:{rows:QuoteRow[];error:string|null}){
 const router=useRouter(),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[busy,setBusy]=useState<number|null>(null),[message,setMessage]=useState('')
 const contracted=(r:QuoteRow)=>!!r.projectId||['contracted','converted'].includes(r.inquiryStatus)
 const visible=rows.filter(r=>(filter==='all'||(filter==='contracted'?contracted(r):filter==='closed'?r.inquiryStatus==='closed':!contracted(r)&&r.inquiryStatus!=='closed'))&&`${r.company} ${r.document.number}`.toLowerCase().includes(query.toLowerCase()))
 async function change(r:QuoteRow,type:'quote'|'contract',status:string){
  if(type==='contract'&&!window.confirm(status==='contracted'?`${r.company}의 계약을 완료하고 견적에 선택된 ${r.document.ai&&r.document.naver?'AI·네이버':r.document.naver?'네이버':'AI'} 관리 프로젝트를 생성할까요?`:`${r.company}을 미계약으로 종료할까요? 상담과 견적은 보관됩니다.`))return
  setBusy(r.inquiryId);setMessage('')
  try{
   const res=await fetch(`/api/discovery/inquiries/${r.inquiryId}${type==='quote'?'/quote':''}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(type==='quote'?{status}:{status,ai_management:r.document.ai,naver_management:r.document.naver})})
   const data=await res.json();if(!res.ok)throw new Error(data.error||'변경 실패')
   setMessage(`${r.company}: ${type==='quote'?'견적 상태를 변경했습니다.':status==='contracted'?'계약 완료 · 관리 프로젝트가 연결되었습니다.':'미계약으로 종료했습니다.'}`);router.refresh()
  }catch(e){setMessage(e instanceof Error?e.message:'상태를 변경하지 못했습니다.')}finally{setBusy(null)}
 }
 return <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:p-6">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-wider text-emerald-700">QUOTATIONS</p><h2 className="mt-1 text-xl font-extrabold">견적서·계약 관리</h2><p className="mt-2 text-sm text-gray-500">저장된 견적을 확인하고 계약·미계약을 처리합니다. 견적 수락과 실제 계약 여부는 각각 기록합니다.</p></div><Link href="/discovery/inquiries/new" className="rounded-lg border px-3 py-2 text-xs font-bold">신규 업체 상담 등록 →</Link></div>
  {error?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{error}</p>:<>
  <div className="mt-5 flex flex-wrap gap-2">{[['all','전체',rows.length],['pending','계약 대기',rows.filter(r=>!contracted(r)&&r.inquiryStatus!=='closed').length],['contracted','계약 완료',rows.filter(contracted).length],['closed','미계약 종료',rows.filter(r=>r.inquiryStatus==='closed').length]].map(([v,l,n])=><button key={v} onClick={()=>setFilter(String(v))} className={`rounded-lg px-3 py-2 text-xs font-bold ${filter===v?'bg-gray-900 text-white':'bg-gray-100 text-gray-600'}`}>{l} {n}</button>)}<input aria-label="견적 업체명·번호 검색" placeholder="업체명·견적번호 검색" value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 rounded-lg border px-3 py-2 text-sm md:ml-auto"/></div>
  {visible.length===0?<p className="mt-5 rounded-xl border border-dashed p-5 text-sm text-gray-500">{rows.length?'조건에 맞는 견적서가 없습니다.':'저장된 견적서가 없습니다. 상담 업체에서 견적서를 작성·저장하면 여기에 표시됩니다.'}</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b text-xs text-gray-500"><tr><th className="py-3">업체·견적번호</th><th>서비스</th><th className="text-right">견적 금액</th><th className="px-4">견적 상태</th><th>계약 여부·처리</th><th className="text-right">열기</th></tr></thead><tbody>{visible.map(r=>{const q=r.document,t=quoteTotals(q),done=contracted(r);return <tr key={r.inquiryId} className="border-b align-top"><td className="py-4"><p className="font-bold">{r.company}</p><p className="mt-1 text-xs text-gray-500">{q.number}</p><p className="mt-1 text-xs text-gray-400">수정 {new Date(r.updatedAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</p></td><td className="py-4 text-xs">{q.ai&&q.naver?'AI·네이버 통합':q.naver?'네이버':'AI 검색'}<p className="mt-1 text-gray-400">{q.months}개월</p></td><td className="py-4 text-right"><p className="font-bold">{money(t.grand)}</p><p className="mt-1 text-xs text-gray-500">월 {money(t.recurring)}</p><p className="mt-1 text-xs text-gray-400">{q.vat?'부가세 포함':'입력 금액 기준'}</p></td><td className="px-4 py-4"><select aria-label={`${r.company} 견적 상태`} disabled={busy!==null} value={q.status} onChange={e=>change(r,'quote',e.target.value)} className="rounded-lg border p-2 text-xs disabled:opacity-50">{Object.entries(quoteStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="py-4"><span className={`text-xs font-bold ${done?'text-emerald-700':r.inquiryStatus==='closed'?'text-gray-500':'text-amber-700'}`}>{done?'계약 완료':r.inquiryStatus==='closed'?'미계약 종료':'계약 대기'}</span>{!done&&<div className="mt-2 flex gap-2"><button disabled={busy!==null} onClick={()=>change(r,'contract','contracted')} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">계약 완료</button>{r.inquiryStatus!=='closed'&&<button disabled={busy!==null} onClick={()=>change(r,'contract','closed')} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-40">미계약 종료</button>}</div>}{done&&r.projectId&&<Link className="mt-2 block text-xs text-emerald-700" href={`/discovery/projects/${r.projectId}`}>관리 프로젝트 →</Link>}</td><td className="py-4 text-right"><Link href={`/discovery/inquiries/${r.inquiryId}?quote=1#quotation`} className="inline-block rounded-lg border px-3 py-2 text-xs font-bold">견적서 열기</Link></td></tr>})}</tbody></table></div>}
  </>}{message&&<p role="status" className="mt-4 rounded-lg bg-gray-50 p-3 text-sm">{message}</p>}
 </section>
}
