'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'

type Profile={description:string|null;industry:string|null;main_services:string|null;target_customer:string|null;service_area:string|null}
const labels=[['industry','업종'],['main_services','주요 서비스'],['target_customer','대상 고객'],['service_area','서비스 지역']] as const
export default function ProjectProfileEditor({id,profile}:{id:number;profile:Profile}){
 const router=useRouter(),[editing,setEditing]=useState(false),[value,setValue]=useState({description:profile.description||'',industry:profile.industry||'',main_services:profile.main_services||'',target_customer:profile.target_customer||'',service_area:profile.service_area||''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(){setBusy(true);setError('');try{const r=await fetch(`/api/discovery/projects/${id}/profile`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const j=await r.json();if(!r.ok)throw new Error(j.error||'저장하지 못했습니다.');setEditing(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 return <div className="mt-4"><button type="button" onClick={()=>{setEditing(!editing);setError('')}} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-bold">{editing?'편집 닫기':'프로젝트 정보 수정'}</button>{editing&&<div className="mt-4 space-y-4 rounded-xl border border-gray-200 bg-gray-50 p-4"><label className="block text-sm font-bold">프로젝트 설명<textarea value={value.description} onChange={e=>setValue({...value,description:e.target.value})} maxLength={3000} rows={4} className="mt-2 w-full rounded-lg border border-gray-300 bg-white p-3 font-normal" placeholder="고객사와 서비스의 핵심 내용을 입력해 주세요."/></label><div className="grid gap-4 md:grid-cols-2">{labels.map(([key,label])=><label key={key} className="block text-sm font-bold">{label}<input value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})} maxLength={1000} className="mt-2 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal"/></label>)}</div><button type="button" disabled={busy} onClick={save} className="rounded-lg bg-[#0A0F1E] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'저장 중...':'변경 내용 저장'}</button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>}</div>
}
