import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
import {requireStaff} from '@/lib/requireStaff'
import {summarizeDiagnosis} from '@/lib/publicDiagnosis'
export const dynamic='force-dynamic'
const date=(v:string)=>new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})
export default async function PublicDiagnoses(){
 await requireStaff()
 const s=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false},global:{fetch:(input,init)=>fetch(input,{...init,cache:'no-store'})}})
 const {data,error}=await s.from('discovery_public_diagnoses').select('id,phone,email,email_status,website_url,snapshot,created_at,retained_until,inquiry_id').gt('retained_until',new Date().toISOString()).order('created_at',{ascending:false}).limit(200)
 return <main className="min-h-screen bg-[#F4F7F6] px-5 pb-12 pt-24"><div className="mx-auto max-w-7xl"><Link href="/discovery" className="text-sm text-emerald-700">← 회사 대시보드</Link><h1 className="mt-4 text-3xl font-bold">고객 직접 사전 진단 목록</h1><p className="mt-3 text-sm text-gray-600">최근 진단 최대 200건입니다. 연락처·이메일·초기 점검 결과를 직원만 확인합니다. 이메일 미입력은 결과 발송을 선택하지 않은 경우입니다. 사전 진단은 상담 신청·연락 요청과 구분해 관리합니다.</p>{error?<p role="alert" className="mt-6 rounded-xl bg-amber-50 p-5">목록을 불러오지 못했습니다. 사전 진단 보관·접수 목록 SQL 적용 여부를 확인해 주세요.</p>:<div className="mt-6 space-y-4">{data?.map(r=>{const d=summarizeDiagnosis(r.snapshot);return <article key={r.id} className="rounded-2xl border bg-white p-6"><div className="grid gap-4 md:grid-cols-4"><div><p className="text-xs text-gray-500">진단 일시</p><p className="mt-1 text-sm">{date(r.created_at)}</p><p className="mt-2 text-xs text-gray-500">보관 종료 {date(r.retained_until)}</p></div><div><p className="text-xs text-gray-500">홈페이지</p><p className="mt-1 break-all text-sm font-bold">{r.website_url}</p></div><div><p className="text-xs text-gray-500">연락처·이메일</p><p className="mt-1 text-sm">{r.phone}</p><p className="mt-1 break-all text-sm">{r.email||'이메일 미입력'}</p><p className="mt-2 text-xs text-gray-500">메일 {({pending:'발송 요청 전',sending:'발송 중',sent:'발송 완료',failed:'발송 실패'} as Record<string,string>)[r.email_status]}</p></div><div>{r.inquiry_id?<Link href={`/discovery/inquiries/${r.inquiry_id}`} className="inline-block rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">연결된 상담 보기 →</Link>:<span className="inline-block rounded-full bg-gray-100 px-3 py-2 text-sm">사전 진단만 진행</span>}</div></div><details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-bold">진단 결과 확인</summary><p className="mt-4">{d.summary}</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{[...d.findings,...d.priorities].map((v,i)=><li key={i}>{v}</li>)}</ul><p className="mt-4 text-xs text-gray-500">{d.notice}</p></details></article>})}{!data?.length&&<p className="rounded-xl bg-white p-6 text-gray-500">보관 중인 고객 사전 진단이 없습니다.</p>}</div>}</div></main>
}
