import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
import {requireStaff} from '../../../lib/requireStaff'

export const dynamic='force-dynamic'
export default async function AiManagement(){
 await requireStaff()
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY
 let projects:{id:number;name:string|null;website_url:string|null}[]=[]
 if(url&&key){const s=createClient(url,key);const {data}=await s.from('discovery_projects').select('id,name,website_url').order('id');projects=data||[]}
 return <main className="min-h-screen bg-[#F4F7F6] px-5 pb-16 pt-24 text-[#0A0F1E] md:px-8"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#087A56]">Damda Discovery · Search & AI</p><h1 className="mt-2 text-3xl font-extrabold md:text-4xl">검색·AI 통합 관리</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-gray-600">SEO·AEO·GEO 관점에서 고객 질문을 만들고 채널별 발견 상태를 측정한 뒤, 확인된 근거로 개선하고 다시 측정합니다.</p></div><Link href="/discovery" className="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-bold">← 회사 대시보드</Link></header><section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-lg font-extrabold">질문과 측정</h2><p className="mt-2 text-sm leading-6 text-gray-500">업체별 질문 엔진에서 반복 측정할 질문을 선정하고 가능한 채널을 측정합니다.</p></article><article className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-lg font-extrabold">원인과 개선</h2><p className="mt-2 text-sm leading-6 text-gray-500">채널별 결과와 근거를 검토해 고칠 일을 정리합니다.</p></article><article className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-lg font-extrabold">재측정과 기록</h2><p className="mt-2 text-sm leading-6 text-gray-500">같은 질문으로 변화를 확인하고 작업 이력을 남깁니다.</p></article></section><section className="mt-7 rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-extrabold">관리 프로젝트</h2><p className="mt-2 text-sm text-gray-500">업체를 선택하면 기존 질문·측정·개선 화면으로 이동합니다.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{projects.map(project=><Link key={project.id} href={`/discovery/projects/${project.id}`} className="rounded-xl border border-gray-200 p-4 transition-colors hover:border-emerald-400"><p className="font-bold">{project.name||`프로젝트 ${project.id}`}</p><p className="mt-1 break-all text-xs text-gray-500">{project.website_url||'홈페이지 미등록'}</p><span className="mt-3 inline-block text-sm font-bold text-[#087A56]">통합 관리 열기 →</span></Link>)}</div>{!projects.length&&<p className="mt-5 text-sm text-gray-500">등록된 프로젝트가 없습니다.</p>}</section></div></main>
}
