import {notFound} from 'next/navigation'
import {createClient} from '@supabase/supabase-js'
import {consultationScope,scopeName} from '../../../lib/consultationScope'
export const dynamic='force-dynamic'
async function getReport(token:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;const s=createClient(url,key,{auth:{persistSession:false},global:{fetch:(input,init)=>fetch(input,{...init,cache:'no-store'})}});const r=await s.from('discovery_diagnosis_reports').select('title,summary,findings,priorities,proposal,published_at,website_snapshot,discovery_inquiries(company_name,website_url,concerns)').eq('public_token',token).eq('status','published').single();return r.data as any}
function safeUrl(value:unknown){if(typeof value!=='string')return null;try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function Finding({text,index}:{text:string;index:number}){
 const match=text.match(/^확인:\s*([\s\S]*?)\s*\|\s*영향:\s*([\s\S]*?)\s*\|\s*근거:\s*([\s\S]*)$/)
 if(!match)return <div className="rounded-xl bg-gray-50 p-5 text-sm leading-6"><b>{index+1}.</b> {text}</div>
 const url=safeUrl(match[3])
 return <article className="rounded-xl border border-gray-100 bg-gray-50 p-5"><p className="text-xs font-bold text-emerald-700">확인한 사실 {index+1}</p><p className="mt-2 text-sm leading-6">{match[1]}</p><p className="mt-4 text-xs font-bold text-gray-500">이 내용의 의미</p><p className="mt-1 text-sm leading-6 text-gray-600">{match[2]}</p><div className="mt-3 border-t pt-3 text-xs text-gray-500">확인 근거: {url?<a href={url} target="_blank" rel="noopener noreferrer" className="break-all text-emerald-700 underline">{url}</a>:match[3]}</div></article>
}
export default async function PublicDiagnosis({params}:{params:{token:string}}){
 const r=await getReport(params.token);if(!r)notFound()
 const i=Array.isArray(r.discovery_inquiries)?r.discovery_inquiries[0]:r.discovery_inquiries, snapshot=r.website_snapshot||{},scope=consultationScope(snapshot,i?.concerns)
 const pages=(Array.isArray(snapshot.pages)?snapshot.pages:[]).filter((p:any)=>!p.error&&safeUrl(p.url)).slice(0,8)
 return <main className="min-h-screen bg-[#F4F7F6] px-5 pb-14 pt-24 text-[#0A0F1E] md:pt-28"><div className="mx-auto max-w-3xl">
 <p className="text-xs font-bold uppercase tracking-[.22em] text-[#0A9B6C]">Damda Discovery · Diagnosis</p><h1 className="mt-3 text-3xl font-extrabold md:text-4xl">{r.title}</h1><p className="mt-3 text-sm text-gray-500">{i?.company_name} · {i?.website_url}</p><p className="mt-2 text-xs text-gray-400">진단 결과 확정 {new Date(r.published_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</p>
 <div className="mt-6 flex flex-wrap gap-2 text-xs"><span className="rounded-full border bg-white px-3 py-2">{scopeName(scope)} 사전 상담</span><span className="rounded-full border bg-white px-3 py-2">홈페이지 {pages.length}개 페이지 확인</span>{scope.naver&&<span className="rounded-full border bg-white px-3 py-2">대표 검색어 {snapshot.naverSelectedQueries?.length||0}개 조회 자료 검토</span>}</div>
 <section className="mt-6 rounded-2xl bg-[#0A0F1E] p-7 text-white"><p className="text-xs font-bold text-[#10E096]">현재 상황을 한눈에</p><p className="mt-3 whitespace-pre-wrap leading-7 text-gray-200">{r.summary}</p></section>
 <section className="mt-5 rounded-2xl border bg-white p-7"><h2 className="text-xl font-extrabold">확인한 사실과 그 의미</h2><p className="mt-2 text-sm text-gray-500">점검에서 확인한 내용과 개선을 검토할 이유를 함께 정리했습니다.</p><div className="mt-5 space-y-4">{(r.findings||[]).map((x:string,index:number)=><Finding key={index} text={x} index={index}/>)}</div></section>
 <section className="mt-5 rounded-2xl border bg-white p-7"><h2 className="text-xl font-extrabold">먼저 할 일</h2><div className="mt-5 space-y-4">{(r.priorities||[]).map((x:string,index:number)=><div key={index} className="flex gap-3 border-b pb-4 last:border-0 last:pb-0"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">{index+1}</span><p className="text-sm leading-6">{x}</p></div>)}</div></section>
 {pages.length>0&&<section className="mt-5 rounded-2xl border bg-white p-7"><h2 className="text-xl font-extrabold">이번에 확인한 홈페이지 자료</h2><p className="mt-2 text-xs text-gray-500">{snapshot.checkedAt?new Date(snapshot.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'점검 당시'} 기준 · 아래 제목과 설명은 점검 당시 확인한 내용입니다.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-emerald-700">확인 페이지와 제목·설명 보기 ({pages.length}개)</summary><div className="mt-4 space-y-3">{pages.map((p:any,index:number)=><article key={index} className="rounded-xl bg-gray-50 p-4"><a href={safeUrl(p.url)!} target="_blank" rel="noopener noreferrer" className="break-all text-sm font-bold text-emerald-700 underline">{p.title||'페이지 제목을 확인하지 못했습니다'}</a><p className="mt-1 break-all text-xs text-gray-400">{p.url}</p><p className="mt-2 text-xs leading-5 text-gray-600">페이지 설명: {p.description||'이번 점검에서 확인하지 못했습니다'}</p></article>)}</div></details></section>}
 <section className="mt-5 rounded-2xl border border-emerald-100 bg-[#EFFFF8] p-7"><h2 className="text-xl font-extrabold">이후 함께 진행할 수 있는 내용</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-gray-700">{r.proposal}</p></section>
 <p className="mt-6 text-xs leading-5 text-gray-400">본 자료는 공개 홈페이지와 선택한 상담 범위의 근거를 검토한 초기 진단입니다. {scope.naver?'네이버 조회 자료는 선택한 검색어와 조회 시점에 한정됩니다. ':''}홈페이지 점검만으로 실제 검색 노출이나 AI 답변의 발견 여부를 판단하지 않으며, 측정이 필요한 사항은 별도 검토합니다.</p>
 </div></main>
}
