'use client'
import {useState,useEffect} from 'react'
import {CustomerReport,reportFromBaseline} from '../../../../lib/caseReportDocument'
export default function CustomerReportEditor({id,initial}:{id:number;initial:any}){
 const [row,setRow]=useState(initial),[doc,setDoc]=useState<CustomerReport>(initial?.draft||reportFromBaseline(initial?.baseline)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function action(action:string){setBusy(true);setError('');setMessage('');try{const r=await fetch(`/api/discovery/inquiries/${id}/customer-report`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,document:{...doc,findings:doc.findings.filter(x=>x.trim()),priorities:doc.priorities.filter(x=>x.trim())}})}),j=await r.json();if(!r.ok)throw new Error(j.error);setRow(j.report);if(action==='prepare')setDoc(j.report.draft);setMessage(action==='publish'?'고객 공개가 확정되었습니다.':action==='unpublish'?'고객 공개를 중단했습니다.':action==='rotate'?'전용 링크를 재발급했습니다. 이전 링크는 열리지 않습니다.':'저장했습니다.')}catch(e){setError(e instanceof Error?e.message:'처리 실패')}finally{setBusy(false)}}
 useEffect(()=>{const handler=(event:Event)=>{const e=event as CustomEvent;if(e.detail.id===id)setDoc(d=>({...d,progress:e.detail.text}))};window.addEventListener('engagement-report',handler);return()=>window.removeEventListener('engagement-report',handler)},[id])
 const url=row?`/client/report/${row.public_token}`:''
 return <section className="mb-6 rounded-2xl border border-emerald-200 bg-white p-6"><h2 className="text-xl font-extrabold">계약 고객 전용 보고 페이지</h2><p className="mt-2 text-sm leading-6 text-gray-600">초기 상담 보고서를 바탕으로 고객에게 전달할 내용을 작성합니다. 초안 저장은 공개된 보고서를 바꾸지 않습니다. 공개 확정 시에만 고객 페이지가 갱신됩니다.</p>{!row?<button disabled={busy} onClick={()=>action('prepare')} className="mt-4 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">상담 보고서로 고객 보고 페이지 준비</button>:<><div className="mt-5 grid gap-4 md:grid-cols-2">{([['title','보고서 제목'],['period','보고 기간'],['summary','현재 상황'],['progress','진행 내용·측정 변화'],['nextSteps','다음 계획']] as const).map(([key,label])=><label key={key} className={key==='title'||key==='period'?'text-sm font-bold':'text-sm font-bold md:col-span-2'}>{label}<textarea rows={key==='title'||key==='period'?1:4} value={doc[key]} onChange={e=>setDoc({...doc,[key]:e.target.value})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label>)}{(['findings','priorities'] as const).map(key=><label key={key} className="text-sm font-bold">{key==='findings'?'확인 근거·진단 (한 줄에 한 항목)':'개선 우선순위 (한 줄에 한 항목)'}<textarea rows={5} value={doc[key].join('\n')} onChange={e=>setDoc({...doc,[key]:e.target.value.split('\n')})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label>)}</div><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>action('save')} className="rounded-xl border px-4 py-3 text-sm font-bold">초안 저장</button><button disabled={busy} onClick={()=>action('publish')} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">고객 공개 확정</button>{row.published&&<><a href={url} target="_blank" rel="noopener noreferrer" className="rounded-xl border px-4 py-3 text-sm font-bold">확정된 고객 페이지 보기 →</a><button disabled={busy} onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+url);setMessage('전용 링크를 복사했습니다.')}catch{setError('링크를 직접 복사해 주세요: '+location.origin+url)}}} className="rounded-xl border px-4 py-3 text-sm font-bold">고객 링크 복사</button><button disabled={busy} onClick={()=>{if(confirm('현재 고객 링크의 공개를 중단할까요?'))action('unpublish')}} className="text-sm text-red-700">공개 중단</button></>}<button disabled={busy} onClick={()=>{if(confirm('기존 전용 링크가 무효화됩니다. 새 링크를 발급할까요?'))action('rotate')}} className="text-sm text-gray-500">전용 링크 재발급</button></div><p className="mt-3 text-xs text-gray-500">{row.published?'고객 공개 중':'고객 비공개 · 초안'} · 링크를 받은 사람이 열람할 수 있습니다. 메일·카카오톡으로 링크를 직접 전달해 주세요.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-bold">계약 전 상담 보고서 보존본</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-gray-600">{row.baseline?.summary||'초기 상담 요약이 없습니다.'}</p></details></>}{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-4 text-sm text-emerald-700">{message}</p>}</section>
}
