'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
type Report={title:string;summary:string;findings:string[];priorities:string[];proposal:string;status:string;public_token:string}
export default function DiagnosisReportEditor({id,initial,scope={ai:true,naver:false},onReport}:{id:number;initial:Report|null;scope?:{ai:boolean;naver:boolean};onReport?:(report:Report)=>void}){
 const router=useRouter(),[report,setReport]=useState<Report|null>(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copyState,setCopyState]=useState<'idle'|'ok'|'fail'>('idle')
 useEffect(()=>{setReport(initial)},[initial])
 const call=async(action:string,payload:any={})=>{setBusy(true);setError('');try{const r=await fetch(`/api/discovery/inquiries/${id}/diagnosis`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'처리에 실패했습니다.');setReport(j.report);onReport?.(j.report);router.refresh();return j.report}catch(e){setError(e instanceof Error?e.message:'처리에 실패했습니다.');return null}finally{setBusy(false)}}
 const save=(action:string)=>report&&call(action,report)
 const updateList=(key:'findings'|'priorities',v:string)=>setReport(r=>r?{...r,[key]:v.split('\n').map(x=>x.trim()).filter(Boolean)}:r)
 const copyLink=async()=>{try{await navigator.clipboard.writeText(location.origin+'/diagnosis/'+report?.public_token);setCopyState('ok');setTimeout(()=>setCopyState('idle'),1800)}catch{setCopyState('fail');setTimeout(()=>setCopyState('idle'),1800)}}
 return <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Customer Diagnosis Report</p><h2 className="mt-1 text-xl font-extrabold">4. 고객용 초기 상담 보고서</h2><p className="mt-2 text-sm text-gray-500">선택한 상담 범위와 확인 근거로 초기 보고서를 작성합니다. 내용을 검토·수정한 뒤 공개 링크를 확정해 고객에게 전달하세요.</p></div>{!report&&<button disabled={busy} onClick={()=>call('generate')} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">{busy?'상담 보고서 생성 중...':scope.naver?'대표 조회로 상담 보고서 만들기':'홈페이지 점검으로 상담 보고서 만들기'}</button>}</div>
 {report&&<div className="mt-6 space-y-4"><label className="block text-sm font-bold">제목<input value={report.title} onChange={e=>setReport({...report,title:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">현재 상태 요약<textarea rows={4} value={report.summary} onChange={e=>setReport({...report,summary:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">확인된 주요 내용 <span className="font-normal text-gray-400">(한 줄에 하나)</span><textarea rows={5} value={report.findings.join('\n')} onChange={e=>updateList('findings',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">우선 개선 항목 <span className="font-normal text-gray-400">(한 줄에 하나)</span><textarea rows={5} value={report.priorities.join('\n')} onChange={e=>updateList('priorities',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">더담다 제안<textarea rows={4} value={report.proposal} onChange={e=>setReport({...report,proposal:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>{if(window.confirm('현재 작성한 보고서를 저장된 근거로 다시 작성합니다. 계속할까요?'))call('generate')}} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">{busy?'보고서 생성 중...':'상담 보고서 다시 생성'}</button><button disabled={busy} onClick={()=>save('save')} className="rounded-xl border px-5 py-3 text-sm font-bold">초안 저장</button><button disabled={busy} onClick={()=>save('publish')} className="rounded-xl bg-[#10E096] px-5 py-3 text-sm font-extrabold text-[#0A0F1E]">{report.status==='published'?'✓ 고객 공개 확정됨':'고객 공개 확정'}</button>{report.status==='published'&&<><a href={`/diagnosis/${report.public_token}`} target="_blank" className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">고객 결과 보기 →</a><button type="button" onClick={copyLink} className="rounded-xl border px-5 py-3 text-sm font-bold">{copyState==='ok'?'✓ 복사 완료':copyState==='fail'?'복사 실패':'링크 복사'}</button></>}</div><p className="text-xs text-gray-400">상태: {report.status==='published'?'고객 공개 확정':'내부 초안'}</p></div>}
 {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</section>
}
