'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
type Report={title:string;summary:string;findings:string[];priorities:string[];proposal:string;status:string;public_token:string}
export default function DiagnosisReportEditor({id,initial}:{id:number;initial:Report|null}){
 const router=useRouter(),[report,setReport]=useState<Report|null>(initial),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const call=async(action:string,payload:any={})=>{setBusy(true);setError('');const r=await fetch(`/api/discovery/inquiries/${id}/diagnosis`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(j.error||'처리에 실패했습니다.');return null}setReport(j.report);router.refresh();return j.report}
 const save=(action:string)=>report&&call(action,report)
 const updateList=(key:'findings'|'priorities',v:string)=>setReport(r=>r?{...r,[key]:v.split('\n').map(x=>x.trim()).filter(Boolean)}:r)
 return <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#0A9B6C]">Customer Diagnosis Report</p><h2 className="mt-1 text-xl font-extrabold">고객용 진단 결과</h2><p className="mt-2 text-sm text-gray-500">초안을 만든 뒤 내용을 직접 확인·수정하고, 확정한 결과만 고객에게 공개합니다.</p></div>{!report&&<button disabled={busy} onClick={()=>call('generate')} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">{busy?'생성 중...':'진단 결과 초안 생성'}</button>}</div>
 {report&&<div className="mt-6 space-y-4"><label className="block text-sm font-bold">제목<input value={report.title} onChange={e=>setReport({...report,title:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">현재 상태 요약<textarea rows={4} value={report.summary} onChange={e=>setReport({...report,summary:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">확인된 주요 내용 <span className="font-normal text-gray-400">(한 줄에 하나)</span><textarea rows={5} value={report.findings.join('\n')} onChange={e=>updateList('findings',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">우선 개선 항목 <span className="font-normal text-gray-400">(한 줄에 하나)</span><textarea rows={5} value={report.priorities.join('\n')} onChange={e=>updateList('priorities',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-bold">더담다 제안<textarea rows={4} value={report.proposal} onChange={e=>setReport({...report,proposal:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>save('save')} className="rounded-xl border px-5 py-3 text-sm font-bold">초안 저장</button><button disabled={busy} onClick={()=>save('publish')} className="rounded-xl bg-[#10E096] px-5 py-3 text-sm font-extrabold text-[#0A0F1E]">고객용 결과 확정</button>{report.status==='published'&&<><a href={`/diagnosis/${report.public_token}`} target="_blank" className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white">고객 결과 보기 →</a><button type="button" onClick={()=>navigator.clipboard.writeText(location.origin+`/diagnosis/${report.public_token}`)} className="rounded-xl border px-5 py-3 text-sm font-bold">링크 복사</button></>}</div><p className="text-xs text-gray-400">상태: {report.status==='published'?'고객 공개 확정':'내부 초안'}</p></div>}
 {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</section>
}
