'use client'
import {useState} from 'react'

type Item={title:string;description:string;link:string;address:string}
type Result={label:string;error?:string;items?:Item[]}
type Report={project:string;query:string;checkedAt:string;results:Result[];trend:{data:{period:string;ratio:number}[];error?:string}|null;shopping:null}
type History={id:number;query:string;interpreted:string;created_at:string}
const channels=[['webkr','웹문서'],['blog','블로그'],['cafearticle','카페글'],['local','지역']] as const
export default function InquiryNaver({inquiryId,initial}:{inquiryId:number;initial:History[]}){
 const[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>(channels.map(x=>x[0])),[trend,setTrend]=useState(true),[report,setReport]=useState<Report|null>(null),[analysis,setAnalysis]=useState(''),[history,setHistory]=useState(initial),[busy,setBusy]=useState(false),[analyzing,setAnalyzing]=useState(false),[error,setError]=useState('')
 async function search(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setReport(null);setAnalysis('');try{const r=await fetch('/api/discovery/naver-explore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inquiryId,query,channels:selected,trend})});const j=await r.json();if(!r.ok)throw new Error(j.error||'조회 실패');setReport(j)}catch(e){setError(e instanceof Error?e.message:'조회 실패')}finally{setBusy(false)}}
 async function analyze(){if(!report)return;setAnalyzing(true);setError('');try{const r=await fetch('/api/discovery/analyze-naver',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inquiryId,report})});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 실패');setAnalysis(j.analysis);setHistory(current=>[{id:j.history.id,query:report.query,interpreted:j.analysis,created_at:j.history.created_at},...current])}catch(e){setError(e instanceof Error?e.message:'분석 실패')}finally{setAnalyzing(false)}}
 return <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-[#087A56]">Pre-contract Naver</p><h2 className="mt-1 text-xl font-extrabold">계약 전 네이버 검색 진단</h2><p className="mt-2 text-sm text-gray-500">상담 업체의 검색 표현을 조회하고 개선안을 저장합니다. 계약하지 않아도 상담 아카이브에 남습니다.</p><form onSubmit={search} className="mt-5 space-y-4"><label className="block text-sm font-bold">고객이 검색할 표현<input required maxLength={80} value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 인천 소상공인 홈페이지" className="mt-2 w-full rounded-xl border border-gray-300 px-4 py-3 font-normal"/></label><div className="flex flex-wrap gap-3">{channels.map(([code,label])=><label key={code} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(code)} onChange={()=>setSelected(current=>current.includes(code)?current.filter(x=>x!==code):[...current,code])}/>{label}</label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={trend} onChange={e=>setTrend(e.target.checked)}/>검색어 트렌드</label></div><button disabled={busy} className="rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'조회 중...':'네이버 검색 조회'}</button></form>
 {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {report&&<div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold">“{report.query}” 조회 결과</p><button onClick={analyze} disabled={analyzing} className="rounded-xl bg-[#087A56] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{analyzing?'분석 중...':'근거 분석·아카이브 저장'}</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{report.results.map((result,i)=><div key={i} className="rounded-xl border p-4"><p className="font-bold">{result.label} · {result.error?'조회 실패':`${result.items?.length||0}건`}</p>{result.error?<p className="mt-2 text-sm text-amber-800">{result.error}</p>:<ol className="mt-2 space-y-2">{result.items?.slice(0,5).map((item,j)=><li key={j} className="text-xs"><a href={item.link} target="_blank" rel="noopener noreferrer" className="font-bold text-[#087A56] hover:underline">{item.title}</a><p className="line-clamp-2 text-gray-500">{item.description||item.address}</p></li>)}</ol>}</div>)}</div>{report.trend&&<p className="mt-3 text-xs text-gray-500">검색어 트렌드: {report.trend.error||`상대 추이 ${report.trend.data.length}개 구간 조회`}</p>}{analysis&&<div className="mt-5 whitespace-pre-wrap rounded-xl bg-emerald-50 p-5 text-sm leading-7">{analysis}</div>}</div>}
 <div className="mt-6"><h3 className="font-extrabold">저장된 네이버 사전 진단</h3>{history.length?<div className="mt-3 space-y-2">{history.map(item=><details key={item.id} className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-bold">{item.query} · {new Date(item.created_at).toLocaleString('ko-KR')}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{item.interpreted}</p></details>)}</div>:<p className="mt-2 text-sm text-gray-500">저장된 네이버 진단이 없습니다.</p>}</div></section>
}
