'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {consultationScope,scopeName} from '../../../../lib/consultationScope'
import {type NaverKeyword,normalizeQueries} from '../../../../lib/naverKeywords'
import WebsiteInspector from '../../WebsiteInspector'
import DiagnosisReportEditor from './DiagnosisReportEditor'
import InquiryNaver from './InquiryNaver'

type Row={query:string;selected:boolean;reason:string;group:string;sourceUrl:string}
export default function InquiryConsultation({id,website,concerns,initial,history}:{id:number;website:string;concerns:string[]|null;initial:any;history:any[]}){
 const router=useRouter(),[report,setReport]=useState(initial),[choice,setChoice]=useState(consultationScope(initial?.website_snapshot,concerns)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[custom,setCustom]=useState('')
 const savedScope=consultationScope(report?.website_snapshot,concerns),snapshot=report?.website_snapshot,queries:string[]=snapshot?.naverSelectedQueries||[],dirty=choice.ai!==savedScope.ai||choice.naver!==savedScope.naver
 function initialRows(snapshot:any):Row[]{const list:Row[]=(snapshot?.naverRecommendations||[]).map((x:NaverKeyword)=>({...x,selected:(snapshot?.naverSelectedQueries||[]).includes(x.query)}));for(const query of snapshot?.naverSelectedQueries||[])if(!list.some(x=>x.query===query))list.push({query,selected:true,reason:'고객 요청 또는 수정한 검색어',group:'고객 요청',sourceUrl:''});return list}
 const[rows,setRows]=useState<Row[]>(initialRows(initial?.website_snapshot))
 useEffect(()=>{setReport(initial);setChoice(consultationScope(initial?.website_snapshot,concerns));setRows(initialRows(initial?.website_snapshot))},[initial,concerns])
 async function call(action:string,payload:any={}){setBusy(true);setError('');try{const response=await fetch(`/api/discovery/inquiries/${id}/naver`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const data=await response.json();if(!response.ok)throw new Error(data.error||'상담 자료 처리 실패');setReport(data.report);setRows(initialRows(data.report.website_snapshot));router.refresh()}catch(e){setError(e instanceof Error?e.message:'상담 자료 처리 실패')}finally{setBusy(false)}}
 function add(){const query=custom.trim();if(!query)return;if(rows.some(x=>x.query.trim()===query)){setError('이미 목록에 있는 검색어입니다.');return}setRows(previous=>[...previous,{query,selected:previous.filter(x=>x.selected).length<3,reason:'고객 요청 검색어',group:'고객 요청',sourceUrl:''}]);setCustom('')}
 function select(){const expressions=normalizeQueries(rows.filter(x=>x.selected).map(x=>x.query));if(!expressions||expressions.length>3){setError('대표 검색어를 1~3개 선택해 주세요.');return}call('select',{queries:expressions})}
 return <><section className="mb-6 rounded-2xl border border-emerald-200 bg-white p-6"><p className="text-xs font-bold text-[#087A56]">계약 전 상담</p><h2 className="mt-2 text-xl font-extrabold">상담 진단 범위</h2><p className="mt-2 text-sm leading-6 text-gray-600">초기 현황과 주요 문제를 확인해 상담 보고서를 제공합니다. 관리 프로젝트는 계약 완료 후 생성되며, 상세 개선 작업·일괄 관리·변경 확인·재측정은 계약 후 진행합니다.</p><div className="mt-4 flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input disabled={busy} type="checkbox" checked={choice.ai} onChange={e=>setChoice({...choice,ai:e.target.checked})}/>검색·AI 사전 진단</label><label className="flex items-center gap-2 text-sm font-bold"><input disabled={busy} type="checkbox" checked={choice.naver} onChange={e=>setChoice({...choice,naver:e.target.checked})}/>네이버 사전 진단</label><button disabled={busy||(!choice.ai&&!choice.naver)} onClick={()=>call('scope',choice)} className="rounded-xl bg-[#087A56] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'처리 중...':'진단 범위 저장'}</button></div><p className="mt-3 text-xs text-gray-500">현재 저장된 범위: {scopeName(savedScope)}{dirty?' · 변경한 범위를 저장하면 해당 진단을 진행할 수 있습니다.':''}</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</section>
 {!dirty&&<>{savedScope.naver?<><section className="mb-6 rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-extrabold">1. 네이버 상담용 홈페이지 초기 점검</h2><p className="mt-2 break-all text-sm text-gray-600">{website}</p><p className="mt-2 text-xs leading-5 text-gray-500">공개 페이지 최대 8개를 확인합니다. 점검 자료와 추천 검색어는 이 상담 건에 보관됩니다.</p><button disabled={busy} onClick={()=>call('inspect')} className="mt-4 rounded-xl bg-[#0A0F1E] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'처리 중...':snapshot?.pages?.length?'홈페이지 초기 점검 다시 실행':'홈페이지 초기 점검'}</button>{snapshot?.pages?.length>0&&<div className="mt-4"><p className="text-sm font-bold">확인 페이지 {snapshot.pageCount}개 · {new Date(snapshot.checkedAt).toLocaleString('ko-KR')}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-bold">홈페이지 점검 근거 보기</summary><div className="mt-3 space-y-3">{snapshot.pages.map((page:any,index:number)=><div key={index} className="rounded-lg bg-gray-50 p-3"><p className="font-bold">{page.title||page.url}</p><p className="mt-1 text-xs text-gray-500">{page.description||page.error||'설명 미확인'}</p></div>)}</div></details></div>}</section>
 <section className="mb-6 rounded-2xl border border-gray-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-extrabold">2. 대표 검색어 추천·선택</h2><p className="mt-2 text-sm text-gray-500">상호·서비스·목적 검색어 중 최대 3개로 초기 상태를 확인합니다.</p></div><button disabled={busy||!snapshot?.pages?.length} onClick={()=>call('recommend')} className="rounded-xl border border-emerald-300 px-4 py-3 text-sm font-bold text-[#087A56] disabled:opacity-50">추천 검색어 만들기</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{rows.map((row,index)=><div key={index} className="rounded-xl border p-3"><div className="flex items-center gap-2"><input aria-label={`${row.query} 선택`} type="checkbox" disabled={busy||(!row.selected&&rows.filter(x=>x.selected).length>=3)} checked={row.selected} onChange={e=>setRows(previous=>previous.map((x,i)=>i===index?{...x,selected:e.target.checked}:x))}/><input aria-label="대표 검색어 수정" maxLength={80} value={row.query} disabled={busy} onChange={e=>setRows(previous=>previous.map((x,i)=>i===index?{...x,query:e.target.value}:x))} className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/></div><p className="mt-2 text-xs leading-5 text-gray-500">{row.group} · {row.reason}</p>{/^https?:\/\//.test(row.sourceUrl)&&<a href={row.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-1 inline-block text-xs font-bold text-[#087A56]">근거 페이지 ↗</a>}</div>)}</div><div className="mt-4 flex gap-2"><input aria-label="고객 요청 검색어 추가" disabled={busy||!snapshot?.pages?.length} value={custom} maxLength={80} onChange={e=>setCustom(e.target.value)} placeholder="고객이 요청한 검색어 추가" className="min-w-0 flex-1 rounded-xl border px-4 py-3 text-sm"/><button disabled={busy||!custom.trim()} onClick={add} className="rounded-xl border px-4 py-3 text-sm font-bold">추가</button></div><button disabled={busy||!rows.some(x=>x.selected)} onClick={select} className="mt-4 rounded-xl bg-[#087A56] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">선택한 대표 검색어 저장 · 초기 조회에 반영</button>{queries.length>0&&<p className="mt-3 text-xs text-gray-500">저장한 검색어: {queries.join(' · ')}</p>}</section>
 <InquiryNaver key={queries.join('|')} inquiryId={id} initial={history} queries={queries}/></>:<><section className="mb-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">저장된 홈페이지 점검 자료</h2>{snapshot?.pages?.length?<><p className="mt-2 text-sm text-gray-600">확인 페이지 {snapshot.pageCount}개 · {new Date(snapshot.checkedAt).toLocaleString('ko-KR')}</p><p className="mt-2 text-xs text-gray-500">고객 보고서는 이 자료를 사용합니다. 홈페이지가 바뀌었다면 아래에서 다시 확인해 자료를 갱신하세요.</p></>:<p className="mt-2 text-sm text-gray-500">아래에서 홈페이지를 확인하면 상담 자료로 저장됩니다.</p>}</section><WebsiteInspector url={website} onResult={async result=>{if(result.consultationTransfer)await call('attach',{transfer:result.consultationTransfer})}}/></>}
 <DiagnosisReportEditor id={id} initial={report?.summary?report:null} scope={savedScope} onReport={setReport}/></>}
 </>
}
