'use client'
import {useEffect,useState} from 'react'
import {closureReasons} from '../../../../lib/caseReportDocument'
import {useRouter} from 'next/navigation'
const labels:Record<string,string>={diagnosis_pending:'진단 대기',reviewing:'진단·검토 중',proposal:'진행 협의',customer_delivery:'고객 전달',quote_drafting:'견적서 작성 중',quote_ready:'견적서 작성 완료',quote_sent:'견적서 전달 완료',contracted:'계약 완료',closed:'상담 종료'}
export default function InquiryActions({id,status,projectId,services,quoteServices}:{id:number;status:string;projectId:number|null;services:{ai:boolean;naver:boolean};quoteServices?:{ai:boolean;naver:boolean}}){
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ai,setAi]=useState(quoteServices?.ai??services.ai),[naver,setNaver]=useState(quoteServices?.naver??services.naver)
 useEffect(()=>{setAi(quoteServices?.ai??services.ai);setNaver(quoteServices?.naver??services.naver)},[services.ai,services.naver,quoteServices?.ai,quoteServices?.naver])
 const [closure,setClosure]=useState({reason:'고객 사유 미확인',customerStatement:'',analysis:'',followUp:''}),[showClosure,setShowClosure]=useState(false)
 const change=async(next:string)=>{if(next==='contracted'&&!projectId){if(!ai&&!naver){setError('이용할 관리 서비스를 하나 이상 선택해 주세요.');return}if(!window.confirm('선택한 서비스로 관리 프로젝트를 생성합니다. 계속할까요?'))return}setBusy(true);setError('');try{const r=await fetch('/api/discovery/inquiries/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next,ai_management:ai,naver_management:naver,closure})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'상태 변경에 실패했습니다.');else router.refresh()}catch{setError('상태 변경에 실패했습니다.')}finally{setBusy(false)}}
 const steps=[['proposal','진행 협의'],['customer_delivery','고객 결과 전달'],['quote_drafting','견적서 작성 시작'],['quote_ready','견적서 작성 완료'],['quote_sent','견적서 전달 완료']] as const
 return <aside className="rounded-2xl border border-gray-200 bg-[#0A0F1E] p-6 text-white shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-[#10E096]">Work Status</p><h2 className="mt-1 text-xl font-extrabold">진단 진행 상태</h2><p className="mt-2 text-sm text-gray-400">현재: {labels[status]||status}</p><div className="mt-6 grid gap-2">
 <button disabled={busy||!!projectId||status==='reviewing'} onClick={()=>change('reviewing')} className="rounded-xl bg-[#10E096] px-4 py-3 text-sm font-extrabold text-[#0A0F1E] disabled:opacity-40">진단·검토 시작</button>
 {steps.map(([value,label])=><button key={value} disabled={busy||!!projectId||status===value} onClick={()=>change(value)} className="rounded-xl border border-white/20 px-4 py-3 text-sm font-bold disabled:opacity-40">{label}</button>)}
 {!projectId&&<fieldset className="mt-3 rounded-xl border border-white/20 p-3"><legend className="px-1 text-xs font-bold">계약 서비스</legend><label className="flex items-center gap-2 py-1 text-sm"><input type="checkbox" disabled={!!quoteServices} checked={ai} onChange={e=>setAi(e.target.checked)}/>AI 진단·관리</label><label className="flex items-center gap-2 py-1 text-sm"><input type="checkbox" disabled={!!quoteServices} checked={naver} onChange={e=>setNaver(e.target.checked)}/>네이버 진단·관리</label>{quoteServices&&<p className="mt-2 text-xs text-gray-300">저장된 견적의 서비스가 계약에 적용됩니다. 변경하려면 견적을 수정·저장하세요.</p>}</fieldset>}
 <button disabled={busy||status==='contracted'} onClick={()=>change('contracted')} className="mt-2 rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-[#0A0F1E] disabled:opacity-40">{projectId?'계약 완료 · 프로젝트 생성됨':'계약 완료 및 프로젝트 생성'}</button>
 {!projectId&&<><button disabled={busy} onClick={()=>setShowClosure(!showClosure)} className="rounded-xl border border-red-400/30 px-4 py-3 text-sm font-bold text-red-200 disabled:opacity-40">미계약 사유 작성 · 아카이브 이동</button>{showClosure&&<div className="rounded-xl border border-white/20 p-4"><label className="block text-sm">미계약 사유<select value={closure.reason} onChange={e=>setClosure({...closure,reason:e.target.value})} className="mt-2 w-full rounded-lg bg-white p-2 text-gray-900">{closureReasons.map(x=><option key={x}>{x}</option>)}</select></label>{([['customerStatement','고객이 밝힌 사유 (없으면 비워 두기)'],['analysis','담당자 검토·배운 점 (필수)'],['followUp','후속 연락·재제안 계획']] as const).map(([key,label])=><label key={key} className="mt-3 block text-xs">{label}<textarea rows={3} value={closure[key]} onChange={e=>setClosure({...closure,[key]:e.target.value})} className="mt-1 w-full rounded-lg bg-white p-2 text-gray-900"/></label>)}<p className="mt-2 text-xs text-gray-400">고객의 실제 설명과 담당자의 추정을 구분합니다. 이 기록은 직원만 확인합니다.</p><button disabled={busy||!closure.analysis.trim()} onClick={()=>change('closed')} className="mt-3 rounded-lg bg-white px-3 py-2 text-sm font-bold text-gray-900 disabled:opacity-40">미계약 보고서 저장 및 상담 종료</button></div>}</>}
 <button disabled={busy||!!projectId||status==='diagnosis_pending'} onClick={()=>change('diagnosis_pending')} className="mt-2 rounded-xl border border-white/20 px-4 py-3 text-xs font-bold text-gray-300 disabled:opacity-40">진단 대기로 되돌리기</button>
 </div><p className="mt-4 text-xs leading-5 text-gray-500">{projectId?'관리 프로젝트에 연결된 계약 건입니다.':'계약 완료 시 상담 정보를 바탕으로 관리 프로젝트를 자동 생성합니다. 미계약 건은 상담 종료로 보관합니다.'}</p>{error&&<p className="mt-4 rounded-lg bg-red-950/50 p-3 text-xs text-red-200">{error}</p>}</aside>
}
